### PR TITLE
Add check on dependent operators on KServe 

### PR DESCRIPTION
**Pull request by zdtsw**
## Description
- similar to what we are doing for codeflare, add check on Kserve
- for code consistency, set to use "cli" instead of "client" in components, since some are calling `client.ObjectKey{}`
- create new function to check operatorCondition which is auto created once operator is installed and removed when operator is uninstalled.
- enabled e2e kserve component
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/434

## How Has This Been Tested?

**update with new commit:**
new test image: quay.io/wenzhou/opendatahub-operator-catalog:v2.9.5-497-4
install ODH operator, but no pipeline operator
Screenshot from 2023-09-05 13-35-20

operator reconcile with error
Screenshot from 2023-09-05 13-35-55

then install pipeline operator 
Screenshot from 2023-09-05 13-37-11

all done
Screenshot from 2023-09-05 13-36-59

**old test on first commit, can ignore below:**
test with: quay.io/wenzhou/opendatahub-operator:dev-2.8.31-1

Screenshot from 2023-08-31 10-45-55
Screenshot from 2023-08-31 10-47-22
Screenshot from 2023-08-31 10-53-43

test with no operators installed but kserve and dsp enabled
then install 3 operators and opendatahub-operator pod stopped reconciliation. 

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by zdtsw** [comment]
mark to draft, so i can work on e2e first

**Comment by zdtsw** [comment]
we should try to get https://github.com/opendatahub-io/opendatahub-operator/pull/509 in first, and then rebase, to get the different codeflare operator name fix

**Comment by zdtsw** [comment]
i did some updates for the e2e test on DSP, if this looks fine, we then can set default Managed to CodeFlare too. 
as for Kserve, still need the fix with modelserving first.

**Comment by VaishnaviHire** [comment]
@zdtsw For this PR we should just add dependent operators check for KServe

We already have a Dashboard check to access OpenShift Pipelines Operator installation for DSP

**Comment by zdtsw** [comment]
local testing:
```
[wenzhou@wenzhou opendatahub-operator]$ make e2e-test
go test ./tests/e2e/ -run ^TestOdhOperator -v --operator-namespace=opendatahub-operator-system "--skip-deletion=false" -timeout 15m 
=== RUN   TestOdhOperator
=== RUN   TestOdhOperator/validate_operator_pod_is_running
I0908 12:25:30.117600 1122635 request.go:682] Waited for 1.000462561s due to client-side throttling, not priority and fairness, request: GET:https://api.wenzhou-rosa-3.wfu1.p3.openshiftapps.com:443/apis/console.openshift.io/v1alpha1?timeout=32s
=== RUN   TestOdhOperator/validate_operator_pod_is_running/validate_ODH_Operator_pod
=== RUN   TestOdhOperator/validate_operator_pod_is_running/validate_CRDs_owned_by_the_operator
=== RUN   TestOdhOperator/create_Opendatahub_components
I0908 12:26:44.833528 1122635 request.go:682] Waited for 1.049398116s due to client-side throttling, not priority and fairness, request: GET:https://api.wenzhou-rosa-3.wfu1.p3.openshiftapps.com:443/apis/mcad.ibm.com/v1beta1?timeout=32s
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test/Creation_of_DataScienceCluster_instance
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components/Validate_Dashboard
=== PAUSE TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components/Validate_Dashboard
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components/Validate_ModelMeshServing
=== PAUSE TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components/Validate_ModelMeshServing
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components/Validate_Kserve
=== PAUSE TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components/Validate_Kserve
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components/Validate_Workbenches
=== PAUSE TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components/Validate_Workbenches
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components/Validate_DataSciencePipelines
=== PAUSE TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components/Validate_DataSciencePipelines
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components/Validate_CodeFlare
=== PAUSE TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components/Validate_CodeFlare
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components/Validate_Ray
=== PAUSE TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components/Validate_Ray
=== CONT  TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components/Validate_Dashboard
=== CONT  TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components/Validate_CodeFlare
=== CONT  TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components/Validate_Ray
=== CONT  TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components/Validate_DataSciencePipelines
=== CONT  TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components/Validate_Workbenches
=== CONT  TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components/Validate_Kserve
=== CONT  TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components/Validate_ModelMeshServing
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_Ownerrefrences_exist
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_Controller_reconcile
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_Component_Enabled_field
=== RUN   TestOdhOperator/delete_components
I0908 12:30:40.267045 1122635 request.go:682] Waited for 1.000203571s due to client-side throttling, not priority and fairness, request: GET:https://api.wenzhou-rosa-3.wfu1.p3.openshiftapps.com:443/apis/flowcontrol.apiserver.k8s.io/v1beta2?timeout=32s
=== RUN   TestOdhOperator/delete_components/e2e-test
=== RUN   TestOdhOperator/delete_components/e2e-test/Deletion:_DataScienceCluster_instance
=== RUN   TestOdhOperator/delete_components/e2e-test/Deletion:_Application_Resource
--- PASS: TestOdhOperator (385.37s)
    --- PASS: TestOdhOperator/validate_operator_pod_is_running (75.09s)
        --- PASS: TestOdhOperator/validate_operator_pod_is_running/validate_ODH_Operator_pod (10.13s)
        --- PASS: TestOdhOperator/validate_operator_pod_is_running/validate_CRDs_owned_by_the_operator (61.03s)
    --- PASS: TestOdhOperator/create_Opendatahub_components (235.37s)
        --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test (231.84s)
            --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test/Creation_of_DataScienceCluster_instance (10.35s)
            --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components (60.19s)
                --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components/Validate_Kserve (10.23s)
                --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components/Validate_Ray (10.35s)
                --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components/Validate_DataSciencePipelines (10.35s)
                --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components/Validate_Dashboard (10.35s)
                --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components/Validate_Workbenches (10.35s)
                --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components/Validate_CodeFlare (120.14s)
                --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_all_deployed_components/Validate_ModelMeshServing (120.14s)
            --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_Ownerrefrences_exist (0.22s)
            --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_Controller_reconcile (20.46s)
            --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_Component_Enabled_field (20.48s)
    --- PASS: TestOdhOperator/delete_components (74.90s)
        --- PASS: TestOdhOperator/delete_components/e2e-test (71.08s)
            --- PASS: TestOdhOperator/delete_components/e2e-test/Deletion:_DataScienceCluster_instance (0.27s)
            --- PASS: TestOdhOperator/delete_components/e2e-test/Deletion:_Application_Resource (70.81s)
PASS
ok      github.com/opendatahub-io/opendatahub-operator/v2/tests/e2e     385.380s
```

**Comment by zdtsw** [comment]
think this is ready for new round of review

**Review by VaishnaviHire — APPROVED** [review]
/lgtm

**Pull request merged**
