### PR TITLE
feat(dspv2): add new images holder in DSPipeline

### PR DESCRIPTION
**Pull request by zdtsw**
## Description

ref: https://issues.redhat.com/browse/RHOAIENG-4173
**the main point is to review the varible name in params.env matches the tobe built image in midstream.** 
covers. https://redhat-internal.slack.com/archives/C05NXTEHLGY/p1709635133042259?thread_ts=1709128195.645739&cid=C05NXTEHLGY 

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by VaishnaviHire — APPROVED** [review]
/lgtm

**Comment by zdtsw** [comment]
/onhold

wait for decision from devops + dsp team

**Comment by VaishnaviHire** [comment]
/hold

Till we get confirmation on image changes

**Review by HumairAK — APPROVED** [review]
/lgtm

**Comment by VaishnaviHire** [comment]
Thanks folks for the confirmation

/hold cancel

**Pull request merged**
