### PR TITLE
Change downstream odh-dashboard ISV new path

### PR DESCRIPTION
**Pull request by zdtsw**
## Description
to make sync from upstream odh-manifests to downstream odh-manifests easy, move ISV to new location.
ref: https://github.com/red-hat-data-services/odh-manifests/pull/446

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by VaishnaviHire** [comment]
/hold

Merge this when downstream path is updated

**Comment by zdtsw** [comment]
oh-hold till https://github.com/red-hat-data-services/odh-manifests/pull/452 is merged in 1.33

**Review by lucferbux — APPROVED** [review]
/lgtm

Let's see if we get the changes merged fro this sprint

**Review by VaishnaviHire — APPROVED** [review]
/lgtm

**Pull request merged**
