### PR TITLE
feat: Add TrustyAI component

### PR DESCRIPTION
**Pull request by ruivieira**
## Description
  
- This PR adds TrustyAI as a component to the ODH operator. 
- This PR targets the `incubation` branch, rather than `main` (as https://github.com/opendatahub-io/opendatahub-operator/pull/568 did).
- TrustyAI operator manifests are now retrieved from the upstream `release/*` branches.

## How Has This Been Tested?

Tested with sample DSC CR including the new
  
```yaml
spec:
  components:
    trustyai:
      managementState: "Managed"
```

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by ruivieira** [comment]
cc @zdtsw @ykaliuta

**Comment by zdtsw** [comment]
@ruivieira i did a test from your code base
`imageParamMap` still need update for:
so the idea is  it should be in the format of "image_name:image_tag"  
take https://github.com/red-hat-data-services/odh-manifests/blob/master/data-science-pipelines-operator/base/params.env as example.
so i would say https://github.com/trustyai-explainability/trustyai-service-operator/blob/release/1.10.1/config/base/params.env will be something like
```
trustyaiServiceImage=quay.io/trustyai/trustyai-service:v0.5.0
trustyaiOperatorImage=quay.io/trustyai/trustyai-service-operator:v1.10.1
```
then we do
```
var imageParamMap = map[string]string{
	"trustyaiServiceImage":  "RELATED_IMAGE_ODH_TRUSTYAI_SERVICE_IMAGE",
	"trustyaiOperatorImage": "RELATED_IMAGE_ODH_TRUSTYAI_OPERATOR_IMAGE",
}
```

**Comment by ruivieira** [comment]
> @ruivieira i did a test from your code base `imageParamMap` still need update for: so the idea is it should be in the format of "image_name:image_tag" take https://github.com/red-hat-data-services/odh-manifests/blob/master/data-science-pipelines-operator/base/params.env as example. so i would say https://github.com/trustyai-explainability/trustyai-service-operator/blob/release/1.10.1/config/base/params.env will be something like
> 
> ```
> trustyaiServiceImage=quay.io/trustyai/trustyai-service:v0.5.0
> trustyaiOperatorImage=quay.io/trustyai/trustyai-service-operator:v1.10.1
> ```
> 
> then we do
> 
> ```
> var imageParamMap = map[string]string{
> 	"trustyaiServiceImage":  "RELATED_IMAGE_ODH_TRUSTYAI_SERVICE_IMAGE",
> 	"trustyaiOperatorImage": "RELATED_IMAGE_ODH_TRUSTYAI_OPERATOR_IMAGE",
> }
> ```

Thanks @zdtsw. I'll change to env format upstream so it matches the expectation here.

**Comment by zdtsw** [comment]
> > @ruivieira i did a test from your code base `imageParamMap` still need update for: so the idea is it should be in the format of "image_name:image_tag" take https://github.com/red-hat-data-services/odh-manifests/blob/master/data-science-pipelines-operator/base/params.env as example. so i would say https://github.com/trustyai-explainability/trustyai-service-operator/blob/release/1.10.1/config/base/params.env will be something like
> > ```
> > trustyaiServiceImage=quay.io/trustyai/trustyai-service:v0.5.0
> > trustyaiOperatorImage=quay.io/trustyai/trustyai-service-operator:v1.10.1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > then we do
> > ```
> > var imageParamMap = map[string]string{
> > 	"trustyaiServiceImage":  "RELATED_IMAGE_ODH_TRUSTYAI_SERVICE_IMAGE",
> > 	"trustyaiOperatorImage": "RELATED_IMAGE_ODH_TRUSTYAI_OPERATOR_IMAGE",
> > }
> > ```
> 
> Thanks @zdtsw. I'll change to env format upstream so it matches the expectation here.

once that is done, i will do a final test and we can get this PR out

**Comment by zdtsw** [comment]
one more thing @ruivieira could you update [https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/components/README.md inthe ](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/components/README.md#integrated-components)

**Comment by zdtsw** [comment]
test on local build, looks good
/lgtm

**Review by zdtsw — APPROVED** [review]
/lgtm

**Pull request merged**
