### PR TITLE
Update resource watches

### PR DESCRIPTION
**Pull request by anishasthana**

### CODE REVIEW

**Comment by crobby** [comment]
Bonus points for the foresight to add imagestreams/buildconfigs in addition to deploymentconfigs

**Comment by anishasthana** [comment]
Seems to have failed at the same spot. I'll try testing it out again tomorrow if it fails again.

**Comment by crobby** [comment]
The error seems pretty consistent.  Maybe a rebase needed to pick up some testing fixes?

**Comment by anishasthana** [comment]
I have the latest changes in via rebase. I'll see if I can figure out what's up.

**Comment by crobby** [comment]
Looks like the same error that is causing other PRs to fail.  I'm absolutely certain that these changes are not the reason for the failures in ci.

**Review by crobby — APPROVED** [review]

**Pull request merged**
