### PR TITLE
ODH Release 1.9 for operator v2.1.0

### LINKED ISSUE #428: Inconsistent default DSCs for different methods of creation
**Describe the bug**
When using different methods for creating the DSC, the default YAML object changes what the user is presented.

**To Reproduce**
When using the `Create DataScienceCluster` button on the DSC tab or the `Create instance` button on the details tab

image

The following object is auto populated:

```yaml
kind: DataScienceCluster
apiVersion: datasciencecluster.opendatahub.io/v1alpha1
metadata:
  labels:
    app.kubernetes.io/created-by: opendatahub-operator
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: datasciencecluster
    app.kubernetes.io/part-of: opendatahub-operator
  name: default
spec:
  components:
    dashboard:
      enabled: false
    datasciencepipelines:
      enabled: false
    distributedworkloads:
      enabled: false
    kserve:
      enabled: false
    modelmeshserving:
      enabled: false
    workbenches:
      enabled: false
```

When using the `Create DataScienceCluster` button on the `DataSciecneCluster required` section of the details tab

image

The following object is auto populated:

```yaml
kind: DataScienceCluster
apiVersion: datasciencecluster.opendatahub.io/v1alpha1
metadata:
  name: default
spec: {}
```

**Expected behavior**
Using both options I would expect the object to auto-populate to something like this:

```yaml
kind: DataScienceCluster
apiVersion: datasciencecluster.opendatahub.io/v1alpha1
metadata:
  name: default
spec:
  components:
    dashboard:
      enabled: true
    datasciencepipelines:
      enabled: true
    distributedworkloads:
      enabled: true
    kserve:
      enabled: true
    modelmeshserving:
      enabled: true
    workbenches:
      enabled: true
```

**Screenshots**

**Additional context**
In previous discussion we have talked about the idea that all of the components should be enabled as true by default, and allow the users to turn off things that they don't want.  By enabling everything by default we are giving new users a default configuration that will allow them to explore all of the components and they can choose to remove components as needed at a later time.

### PR DESCRIPTION
**Pull request by VaishnaviHire**
Release PR for manifests version 1.9

Also Fixes #428 
## Description

Dev Catalog: quay.io/vhire/opendatahub-operator-catalog:v2.1.0

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by VaishnaviHire** [comment]
With dev catalog, all pods are deployed successfully except `mcad-controller`
```
✗ oc get po -n opendatahub 
NAME                                                              READY   STATUS             RESTARTS      AGE
data-science-pipelines-operator-controller-manager-79f6489kz8f7   1/1     Running            0             12m
etcd-74f9649477-hrt68                                             1/1     Running            0             12m
instascale-instascale-7f4d7f5bf5-kpbnz                            1/1     Running            0             12m
kuberay-operator-6ff867bb84-s7j8x                                 1/1     Running            0             12m
mcad-controller-mcad-77dcb5b9c-8dcf8                              0/1     CrashLoopBackOff   9 (22s ago)   12m
modelmesh-controller-77d95f9ccf-ht6pw                             1/1     Running            0             12m
modelmesh-controller-77d95f9ccf-rm6jf                             1/1     Running            0             12m
modelmesh-controller-77d95f9ccf-sp2tg                             1/1     Running            0             12m
notebook-controller-deployment-599f95d8fd-rbz7b                   1/1     Running            0             12m
odh-dashboard-995f8bc9d-8l57q                                     2/2     Running            0             12m
odh-dashboard-995f8bc9d-lsdhr                                     2/2     Running            0             12m
odh-model-controller-8d7cf5dc9-6jckh                              1/1     Running            0             12m
odh-model-controller-8d7cf5dc9-r972q                              1/1     Running            0             12m
odh-model-controller-8d7cf5dc9-ww4sx                              1/1     Running            0             12m
odh-notebook-controller-manager-75f677c77f-sdpdf                  1/1     Running            0             12m

```

**Comment by VaishnaviHire** [comment]
mcad controller fails with following error
```
I0823 13:36:50.416941       1 reflector.go:255] Listing and watching *v1.Pod from go/pkg/mod/k8s.io/client-go@v0.20.0/tools/cache/reflector.go:167
E0823 13:36:50.418339       1 reflector.go:138] go/pkg/mod/k8s.io/client-go@v0.20.0/tools/cache/reflector.go:167: Failed to watch *v1.Pod: failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:opendatahub:mcad-controller-mcad" cannot list resource "pods" in API group "" at the cluster scope
I0823 13:36:51.346651       1 reflector.go:255] Listing and watching *v1beta1.AppWrapper from go/pkg/mod/k8s.io/client-go@v0.20.0/tools/cache/reflector.go:167
E0823 13:36:51.348861       1 reflector.go:138] go/pkg/mod/k8s.io/client-go@v0.20.0/tools/cache/reflector.go:167: Failed to watch *v1beta1.AppWrapper: failed to list *v1beta1.AppWrapper: appwrappers.mcad.ibm.com is forbidden: User "system:serviceaccount:opendatahub:mcad-controller-mcad" cannot list resource "appwrappers" in API group "mcad.ibm.com" at the cluster scope
```

**Comment by zdtsw** [comment]
did a local build based on "main" branch, as `quay.io/wenzhou/opendatahub-operator-catalog:v2.8.23-0 `
installed it and enabled all components except kserve,
could not see issue of codeflare 
Screenshot from 2023-08-23 16-22-21

**Comment by zdtsw** [comment]
looks fine with use v1.9 as `MANIFEST_RELEASE` too

**Comment by VaishnaviHire** [comment]
What is the `mcad-controller` image being used? Can you add logs. I rebase and still see the error

https://github.com/opendatahub-io/opendatahub-operator/pull/465#issuecomment-1690059113

**Comment by VaishnaviHire** [comment]
Seemed like an outdated cluster role issue, worked fine after clean install

**Review by LaVLaS — APPROVED** [review]
/unhold

**Pull request merged**
