### PR TITLE
Add missing resources to manage in DSC controller

### PR DESCRIPTION
**Pull request by ykaliuta**
## Description

Extend the list of resources to include resource types previously defined in v1 
Add required RBAC permissions.

## How Has This Been Tested?

Deployed the operator, deployed a Cluster. Removed ImageStreams -- respawned. Removed Cluster -- objects removed including ImageStreams.

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by zdtsw — APPROVED** [review]
/lgtm

still need fix linter

**Comment by ykaliuta** [comment]
> /lgtm
> 
> still need fix linter

To be sure, we are not talkig about PR's problem, right?

```
% golint controllers/datasciencecluster/datasciencecluster_controller.go
controllers/datasciencecluster/datasciencecluster_controller.go:60:6: type name will be used as datasciencecluster.DataScienceClusterReconciler by other packages, and that stutters; consider calling this Reconciler
controllers/datasciencecluster/datasciencecluster_controller.go:71:6: type name will be used as datasciencecluster.DataScienceClusterConfig by other packages, and that stutters; consider calling this Config
controllers/datasciencecluster/datasciencecluster_controller.go:142:10: if block ends with a return statement, so drop this else and outdent its block
controllers/datasciencecluster/datasciencecluster_controller.go:278:9: if block ends with a return statement, so drop this else and outdent its block
controllers/datasciencecluster/datasciencecluster_controller.go:388:11: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
```

**Comment by zdtsw** [comment]
> > /lgtm
> > still need fix linter
> 
> To be sure, we are not talkig about PR's problem, right?
> 
> ```
> % golint controllers/datasciencecluster/datasciencecluster_controller.go
> controllers/datasciencecluster/datasciencecluster_controller.go:60:6: type name will be used as datasciencecluster.DataScienceClusterReconciler by other packages, and that stutters; consider calling this Reconciler
> controllers/datasciencecluster/datasciencecluster_controller.go:71:6: type name will be used as datasciencecluster.DataScienceClusterConfig by other packages, and that stutters; consider calling this Config
> controllers/datasciencecluster/datasciencecluster_controller.go:142:10: if block ends with a return statement, so drop this else and outdent its block
> controllers/datasciencecluster/datasciencecluster_controller.go:278:9: if block ends with a return statement, so drop this else and outdent its block
> controllers/datasciencecluster/datasciencecluster_controller.go:388:11: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
> ```

yes correct.
i think these are only the from linter.

**Comment by ykaliuta** [comment]
> @ykaliuta can you fix the code for checks?

Sorry, I got a bit lost in the messages. Fixing.
I see non-required golangci-lint is failing, but the lines are not part of the PR, wil ignore it
```

controllers/datasciencecluster/datasciencecluster_controller.go:28: File is not `gci`-ed with -s standard,default,blank,prefix(github.com/opendatahub-io/opendatahub-operator),blank,dot (gci)
        "github.com/hashicorp/go-multierror"
controllers/datasciencecluster/datasciencecluster_controller.go:29: File is not `gci`-ed with -s standard,default,blank,prefix(github.com/opendatahub-io/opendatahub-operator),blank,dot (gci)
        v1 "github.com/openshift/api/operator/v1"
controllers/datasciencecluster/datasciencecluster_controller.go:33: File is not `gci`-ed with -s standard,default,blank,prefix(github.com/opendatahub-io/opendatahub-operator),blank,dot (gci)
        authv1 "k8s.io/api/rbac/v1"
```

**Comment by VaishnaviHire** [comment]
@ykaliuta Since this PR makes changes in the operator `/config` files, you would need to update operator bundle by using following command

```
make manifests bundle 
```

**Comment by ykaliuta** [comment]
> @ykaliuta Since this PR makes changes in the operator `/config` files, you would need to update operator bundle by using following command
> 
> ```
> make manifests bundle 
> ```

Thanks!

**Review by VaishnaviHire — APPROVED** [review]
Thanks for the PR @ykaliuta 

/lgtm

**Pull request merged**
