### PR TITLE
[cherry-pick] Add logic for applying monitoring stack

### PR DESCRIPTION
**Pull request by zdtsw**
## Description
cherry-pick from https://github.com/red-hat-data-services/rhods-operator/pull/67

ref: https://github.com/opendatahub-io/opendatahub-operator/issues/357

## How Has This Been Tested?

local build: quay.io/wenzhou/opendatahub-operator-catalog:v2.11.357-5
default ODH components have no problem to start up

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by zdtsw** [comment]
> /hold
> 
> @zdtsw Should we hold this till we have #605 merged, as both PRs introduce major code changes across components?

i dont mind waiting. this is only the part from downstream backport to ODH.
i guess the only difficulty is to resolve rebase and conflicts if we want to sync from ODH main to downstream main.

**Comment by VaishnaviHire** [comment]
Moving ahead with merge, as this change won't affect odh platform.

/hold cancel

**Pull request merged**
