### PR TITLE
Update Owners-aliases list

### PR DESCRIPTION
**Pull request by Sara4994**
## Description

This PR updates the owners-aliases list in the repository with the Github ID's of new members in the team

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by VaishnaviHire** [comment]
Thanks for the PR @Sara4994 . As part of this PR can we remove all other aliases and only keep `platform` ? The tide behavior is not as expected, so lets just have the platform team as part of owners file

**Comment by Sara4994** [comment]
> Thanks for the PR @Sara4994 . As part of this PR can we remove all other aliases and only keep `platform` ? The tide behavior is not as expected, so lets just have the platform team as part of owners file

@VaishnaviHire Yep sure, i have removed other aliases leaving only platform.

**Comment by VaishnaviHire** [comment]
We would need to cleanup from [OWNERS](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/OWNERS#L5-L12) file as well

**Comment by Sara4994** [comment]
> We would need to cleanup from [OWNERS](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/OWNERS#L5-L12) file as well

@VaishnaviHire yep my bad... this is done now

**Pull request merged**
