### PR TITLE
Rebase to kfctl 21a836d

### PR DESCRIPTION
**Pull request by vpavlin**

### CODE REVIEW

**Comment by vpavlin** [comment]
Image available at quay.io/opendatahub/opendatahub-operator:pr-71

**Comment by crobby** [comment]
How do we want to handle the OWNERS file stuff?

**Comment by LaVLaS** [comment]
Initial tests with the rebased operator were good. I had some cluster issues that I need resolve then I can re-test to confirm `lgtm`

**Review by LaVLaS — APPROVED** [review]
/lgtm

Components deployed successfully and tests ran clean.

**Review by nakfour — APPROVED** [review]

**Comment by nakfour** [comment]
I tested this rebase with Openshift stacks in this PR (https://github.com/kubeflow/manifests/pull/1567)  and it worked.

**Pull request merged**
