### PR TITLE
[RFC] feat: pass platform from env variable and fall back to use old logic

### PR DESCRIPTION
**Pull request by zdtsw**
## Description

- introduce new env var ODH_PLATFORM_TYPE
- rename old function to DetectPlatform
- create new GetPlatform to check env first or fall to call DetectPlatform
- move old call cluster.GetPlatform, either pass as parameter or out of subcomponent reconcile

## How Has This Been Tested?

local build:  quay.io/wenzhou/opendatahub-operator-catalog:v2.18.913-0 without setting new env == the old way 
operator pod: print `{"level":"info","ts":"2024-09-13T11:07:12Z","logger":"setup","msg":"running on","platform":"Open Data Hub"}`
by adding in CSV
```
- name: PLATFORM
  value: SelfManagedRHOAI
```
oprator pod print `{"level":"info","ts":"2024-09-13T11:06:38Z","logger":"setup","msg":"running on","platform":"OpenShift AI Self-Managed"}`
 

## Merge criteria

- [ ] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [ ] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [ ] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by ykaliuta** [comment]
The patch contains much more changes than in description

**Comment by lburgazzoli** [comment]
quck note: ideally, env vars should have a domain prefix to avoid any conflict, i.e. ODH_

**Comment by zdtsw** [comment]
> quck note: ideally, env vars should have a domain prefix to avoid any conflict, i.e. ODH_

but we are having 2 different env variable in upstream and downstream: ODH_PLATFORM and RHOAI_PLATFORM
or, we have ODH_PLATFORM for both?

**Comment by zdtsw** [comment]
> The patch contains much more changes than in description

the main change is the "env part" but since it reuses the old function name, then the old function have to get a new name.

as for the part of "removing duplicated calls (of old function) and use parameters" it is not stated in the draft's title, only in the description.

**Comment by ykaliuta** [comment]
> > The patch contains much more changes than in description
> 
> the main change is the "env part" but since it reuses the old function name, then the old function have to get a new name.
> 
> as for the part of "removing duplicated calls (of old function) and use parameters" it is not stated in the draft's title, only in the description.

I see the change as you keep API the same and only change implementation under the hood.
I have https://github.com/opendatahub-io/opendatahub-operator/pull/1059 then I cannot rebase to discuss.

**Comment by lburgazzoli** [comment]
> > quck note: ideally, env vars should have a domain prefix to avoid any conflict, i.e. ODH_
> 
> but we are having 2 different env variable in upstream and downstream: ODH_PLATFORM and RHOAI_PLATFORM or, we have ODH_PLATFORM for both?

I'd say `ODH_` shoud be enough, my understanding is that i.e. for related images we still use `ODH`, like https://github.com/red-hat-data-services/rhods-operator/blob/76acc49b4e14b5ad6e63c8bdd8c194c9335c417c/components/ray/ray.go#L62C45-L62C63

**Comment by ykaliuta** [comment]
In general, I support passing data to functions explicitly instead of look up from some global state inside. As much as possible. Usually it in addition makes functions more testable. But it is just a different change.

**Comment by ykaliuta** [comment]
Can it be splitted into 2 PRs -- passing platform as a parameter, and introducing environment variable?
If the first one is just a simple refactoring, the second changes functionality and deserves more attention/discussion.

**Comment by zdtsw** [comment]
> Can it be splitted into 2 PRs -- passing platform as a parameter, and introducing environment variable? If the first one is just a simple refactoring, the second changes functionality and deserves more attention/discussion.

can do that. 
can get the refactor out first, and leave the "env" part once we are ready for "refinement"

**Comment by zdtsw** [comment]
close in favor of 2 following PRs

**Pull request closed without merging**
