### PR TITLE
ODH Release bundle for v2.0.0

### LINKED ISSUE #311: ODH Release Tracker (v2.0.0)
Following tasks need to be completed for ODH release

- Upgrade from existing operator

- Documentation requirements
  - Contributors Guide 
  -  Opendatahub.io blog and documentation
  - Quick Install - https://opendatahub.io/docs/quick-installation/
  - How to deploy different profiles
  - FAQ?

- Testing requirements
  -  Unit tests
  - E2e testing

- Resolve existing bugs/features

- Implementation of Image parameters 
- Add New Core Components
     - KServe

### PR DESCRIPTION
**Pull request by VaishnaviHire**
Fixes #311 
## Description
Release Bundle for ODH release 1.8

Channel : `fast`
Operator Version: v2.0.0
Manifest Version :  v1.8

**Note**: CSV image will be replaced in OperatorHub PR

## How Has This Been Tested?
1. E2e test job
2. Manifests will be tested once we have 1.8 version

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by VaishnaviHire** [comment]
OperatorHub PR - https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/2997

**Review by etirelli — APPROVED** [review]
lgtm

**Pull request merged**
