### PR TITLE
Add finalizer for DSCI and DSC

### PR DESCRIPTION
**Pull request by zdtsw**
## Description
- add finalizer to DSC and DSCI instance.
- this wont help when we click "uninstall operator" to auto delete DSC/DSCI CR
- this only happens when we manually click "delete" or from "oc delete" on the DSCI/DSC CR, which shows in operator pod's log

## How Has This Been Tested?
local build: quay.io/wenzhou/opendatahub-operator-catalog:v2.8.21-2

Screenshot from 2023-08-21 13-10-28
then create a DSC instance
Screenshot from 2023-08-21 13-27-43

check Yaml, it got finalizer set as well.

Screenshot from 2023-08-21 13-25-35

then delete this instance
it is gone
Screenshot from 2023-08-21 13-26-00

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
@VaishnaviHire  @zdtsw This would be great to have as it gives a way to hook cleanup logic for objects created e.g. for Service Mesh setup. When this PR could be merged? Happy to help with the review if needed.

**Comment by zdtsw** [comment]
> @VaishnaviHire @zdtsw This would be great to have as it gives a way to hook cleanup logic for objects created e.g. for Service Mesh setup. When this PR could be merged? Happy to help with the review if needed.

Thanks @bartoszmajsak if you can spare some time to review it,  that would be great.
I made it a long time ago, but since no issue created for such and with low priority it did not get much attention.

We will not have time to get this out by this week due to busy ODH release, but if we can finalize the code, it is nice to have it merged maybe next week(s)

**Comment by zdtsw** [comment]
close this in favor of https://github.com/opendatahub-io/opendatahub-operator/pull/605

**Pull request closed without merging**
