### PR TITLE
Feature: add networkpolicy in dsci

### PR DESCRIPTION
**Pull request by zdtsw**
## Description
ref  https://github.com/opendatahub-io/opendatahub-operator/issues/423

## How Has This Been Tested?
local build : 
http://quay.io/wenzhou/opendatahub-operator-catalog:v2.10.423-10

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by asanzgom** [comment]
So far I checked on an AWS Cluster the installation of the http://quay.io/wenzhou/opendatahub-operator-catalog:v2.10.423-10 image and was able to access ODH dashboard:

image

Here I leave the networkpolicy-opendatahub.yaml : 

```kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: opendatahub
  namespace: opendatahub
  uid: 0d0c50dd-2ff0-4c69-b6f0-8b6840f2b480
  resourceVersion: '397359'
  generation: 1
  creationTimestamp: '2023-10-03T12:49:35Z'
  ownerReferences:
    - apiVersion: dscinitialization.opendatahub.io/v1
      kind: DSCInitialization
      name: default
      uid: d6c9aba5-9d52-4570-858e-35de6b0e8d06
      controller: true
      blockOwnerDeletion: true
  managedFields:
    - manager: manager
      operation: Update
      apiVersion: networking.k8s.io/v1
      time: '2023-10-03T12:49:35Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:ownerReferences':
            .: {}
            'k:{"uid":"d6c9aba5-9d52-4570-858e-35de6b0e8d06"}': {}
        'f:spec':
          'f:ingress': {}
          'f:policyTypes': {}
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              opendatahub.io/generated-namespace: 'true'
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-ingress
  policyTypes:
    - Ingress
status: {}
```

Now trying to test on a PSI Cluster

**Review by asanzgom — APPROVED** [review]

**Review by jgarciao — APPROVED** [review]
I've tested the livebuild in an OpenStack cluster and it worked well

**Comment by asanzgom** [comment]
Test on PSI Cluster by @jgarciao went fine, also spawned notebooks correctly

**Comment by VaishnaviHire** [comment]
@zdtsw Just want to confirm if there were any failures in pipelines, data science projects or any other components

**Comment by zdtsw** [comment]
> @zdtsw Just want to confirm if there were any failures in pipelines, data science projects or any other components

i think we can run odh nightly on the build to ensure no error from this change, this will not be sync to downstream till all cases are verified. 
but from QE said, they did not see other errors.

**Comment by bartoszmajsak** [comment]
@zdtsw I think this should be changed to `It` then https://github.com/opendatahub-io/opendatahub-operator/pull/584#discussion_r1342752851

**Comment by zdtsw** [comment]
> @zdtsw I think this should be changed to `It` then [#584 (comment)](https://github.com/opendatahub-io/opendatahub-operator/pull/584#discussion_r1342752851)

correct! thanks for bringing this up.

**Pull request merged**
