### PR TITLE
Dockerfile: merges manifests builder stages to one

### PR DESCRIPTION
**Pull request by ykaliuta**
We can combine two build stages into one, as there is no need to always build both images (not done by podman) to only then decide from which one we want to copy manifests to the target image. Instead manifests stage will either copy local manifests or fetches using the script based on USE_LOCAL argument.

Move USE_LOCAL and OVERWIRTE_MANIFESTS args under FROM since args have scope of the FROM they are declared in.

It requires opt/manifests directory to exist, but since it's a part of git repo, it's fine.

Original patch from: Bartosz Majsak <bartosz.majsak@gmail.com> [1]

[1] https://github.com/opendatahub-io/opendatahub-operator/pull/773

## Merge criteria

- [ ] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [ ] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [ ] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by zdtsw — APPROVED** [review]

**Comment by ykaliuta** [comment]
rebased

**Comment by ykaliuta** [comment]
@zdtsw sorry for disturbing, but could you recheck it after rebase?

**Review by zdtsw — APPROVED** [review]

**Pull request merged**
