### PR TITLE
feat: adds `EnabledWhen`  to the builder

### PR DESCRIPTION
**Pull request by bartoszmajsak**
## Description

With this construct, we can have features toggled conditionally, for example, based on the target platform, management mode or particular resource not existing (yet) in the cluster.  It's part of upcoming work around network policies but I decided to break down this work to smaller PRs.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by zdtsw** [comment]
can you give me an example how you want to invoke this fb.EnabledWhen().
i thought by calling this method will eventully make feature to be disabled instead of enabled.....

**Comment by bartoszmajsak** [comment]
> can you give me an example how you want to invoke this fb.EnabledWhen(). i thought by calling this method will eventully make feature to be disabled instead of enabled.....

@zdtsw I am not sure I understand your last point, but let me give you a code example. Maybe this will clear things out

```golang
smcpCreation, errSmcp := feature.CreateFeature("mesh-control-plane-creation").
	For(s.DSCInitializationSpec).
	EnabledWhen(servicemesh.ControlPlaneDoesNotExist).
	Manifests(
		path.Join(rootDir, templatesDir, "base", "create-smcp.tmpl"),
	).
	PreConditions(
		servicemesh.EnsureServiceMeshOperatorInstalled,
		feature.CreateNamespaceIfNotExists(serviceMeshSpec.ControlPlane.Namespace),
	).
	PostConditions(
		feature.WaitForPodsToBeReady(serviceMeshSpec.ControlPlane.Namespace),
	).
	Load()
```

so `EnabledWhen(servicemesh.ControlPlaneDoesNotExist)` will make sure this is only getting applied when SMCP of a given name is not there yet. This can also go further with the use of different target platforms.

**Review by israel-hdez — COMMENTED** [review]
This seems to be the only loader `func` that would run its argument on `Load()`. I think it is by design.

I think I'd appreciate a comment describing that the `enabled` argument must not return `false` by mistake by properly distinguishing owned resources. For example, in [your example](https://github.com/opendatahub-io/opendatahub-operator/pull/793#issuecomment-1880615596) the `servicemesh.ControlPlaneDoesNotExist` must properly identify an SMCP resource created/owned by the odh-operator and not disable the feature in such case, for consistency.

**Comment by bartoszmajsak** [comment]
> This seems to be the only loader func that would run its argument on Load(). I think it is by design.

@israel-hdez It's a `partialBuilder` (maybe we need a better name here) and will be applied the same way as any other (such as pre or post condition) here:

https://github.com/opendatahub-io/opendatahub-operator/blob/9982a07e97c3e4c1e545af3c19d751aafaa105ad/pkg/feature/builder.go#L153-L157

What do you mean by it being the only `func` that runs its argument on `Load()`? 

> `servicemesh.ControlPlaneDoesNotExist` must properly identify an SMCP resource created/owned by the odh-operator and not disable the feature in such case, for consistency.

I am not quite sure we are on the same page here :) This given example does NOT intend to trigger "create SMCP" when an SMCP of a matching name exists in the given namespace. Think of it as a simple feature flag (in fact the field is already in the struct, so this only exposes it in the builder and opens for applying different rules)

Perhaps it's misleading at this point, as creating resources using templates will be skipped if it already exists: https://github.com/opendatahub-io/opendatahub-operator/blob/9982a07e97c3e4c1e545af3c19d751aafaa105ad/pkg/feature/raw_resources.go#L63-L68

We might need it for handling e.g. different paths for different platforms

**Comment by israel-hdez** [comment]
> What do you mean by it being the only `func` that runs its argument on `Load()`?
> 

What I wanted to mean is that, in your example, for this line:

```
EnabledWhen(servicemesh.ControlPlaneDoesNotExist).
```

The `servicemesh.ControlPlaneDoesNotExist` argument will be invoked when you do `fb.Load()`. In contrast, for the rest of the builder funcs (e.g. `PreConditions`) the argument (or any effects related to the arguments) is simply set/added to a field/list of the `Feature` and the invocation is done when you do `feature.Apply()`.

> > `servicemesh.ControlPlaneDoesNotExist` must properly identify an SMCP resource created/owned by the odh-operator and not disable the feature in such case, for consistency.
> 
> I am not quite sure we are on the same page here :) This given example does NOT intend to trigger "create SMCP" when an SMCP of a matching name exists in the given namespace. Think of it as a simple feature flag (in fact the field is already in the struct, so this only exposes it in the builder and opens for applying different rules)

I was thinking more in consistency for a sub-sequent run. In your example, if the cluster is clean the feature would be enabled. Then, because of the `Manifests` the Control Plane would be created. Once created, a subsequent run may result in the feature being turned off if the checking func (in your example it is `servicemesh.ControlPlaneDoesNotExist`) does not account for it. That could be problematic, or not... depending on how the feature is implemented.

I guess it will be problematic if there is any `OnDelete` hook in the `Feature`. Otherwise, the cluster would do the cleanup by itself.

**Comment by israel-hdez** [comment]
Just note... I'm good with the code.

I just want a comment to make it clear to other devs about these little details that can cause issues.

**Comment by bartoszmajsak** [comment]
> The servicemesh.ControlPlaneDoesNotExist argument will be invoked when you do fb.Load().

@israel-hdez Clearly it was too late for me, after the morning coffee I understood what you mean :) 

So yeah, this is by (accidental) design that it is not deferred to actual `Feature` execution. The only reason right now is to not create an associated feature tracker instance. This, however, is entirely wrong :D  I reworked it in another PR #795

**Comment by bartoszmajsak** [comment]
> I was thinking more in consistency for a sub-sequent run. In your example, if the cluster is clean the feature would be enabled. Then, because of the Manifests the Control Plane would be created. Once created, a subsequent run may result in the feature being turned off if the checking func (in your example it is servicemesh.ControlPlaneDoesNotExist) does not account for it. That could be problematic, or not... depending on how the feature is implemented.
> 
> I guess it will be problematic if there is any OnDelete hook in the Feature. Otherwise, the cluster would do the cleanup by itself.

The delete hook is a good example which makes me believe the whole "clean-up from the previous state if now disabled" needs to be taken into account and is missing in this simply looking PR. My thinking was that this is more about some static conditions (such as the type of platform), but your perspective made me realize I need to revise some things here :) Thank you.

From the top of my head if the feature was previously enabled (this can be based on the existence of `FeatureTracker` resource), we should:
- call delete hooks if any
- delete FeatureTracker instance

WDYT @israel-hdez?

**Comment by israel-hdez** [comment]
> From the top of my head if the feature was previously enabled (this can be based on the existence of `FeatureTracker` resource), we should:
> 
>     * call delete hooks if any
> 
>     * delete FeatureTracker instance

To me this makes sense.
Although my comment still applies: the func passed to `EnabledWhen(...)` needs to be careful and consistently return `true` when needed.

**Comment by bartoszmajsak** [comment]
> Although my comment still applies: the func passed to `EnabledWhen(...)` needs to be careful and consistently return `true` when needed.

That's right, I will add documentation together if the cleanup logic handling.

**Comment by bartoszmajsak** [comment]
Superseded by #1057

**Pull request closed without merging**
