### PR TITLE
Odh 2.11.0 release

### PR DESCRIPTION
**Pull request by VaishnaviHire**
## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by shalberd** [comment]
why is this a part of ODH 2.35.0?
v2.35.0
Screenshot 2025-10-06 at 15 04 12

**Comment by zdtsw** [comment]
i think the relase note generator is wrong,
it somehow gets the change log from 2.11 to 2.35

**Comment by shalberd** [comment]
Hi ZhouWen

Ok, can you please make a ticket RHOAIENG so this gets looked at?

Thank you very much and I am glad it is not a code-related / merge issue itself, just regarding to release notes.

**Comment by zdtsw** [comment]
> Hi ZhouWen
> 
> Ok, can you please make a ticket RHOAIENG so this gets looked at?
> 
> Thank you very much and I am glad it is not a code-related / merge issue itself, just regarding to release notes.

no wrries!
here is the issue https://issues.redhat.com/browse/RHOAIENG-35574 to track the fix.

**Pull request merged**
