### PR TITLE
feat: add default managementstate to only ModelReg if it was not set in DSC CR

### PR DESCRIPTION
**Pull request by zdtsw**
## Description

- for upgrade case if DSC CR does not have MR component, with this change it will show as Removed
- keep other components as-is (do not set Removed if upgrade from very old release to new one which has components)

https://issues.redhat.com/browse/RHOAIENG-14194 

## Merge criteria

- [ ] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [ ] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [ ] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by zdtsw** [comment]
seems either we directly set in the Component which apply to all components or we cannot directly use kubebuilder on ModelReg only

**Comment by zdtsw** [comment]
> seems either we directly set in the Component which apply to all components or we cannot directly use kubebuilder on ModelReg only

or do like this to override, not sure if this is good idea?

**Comment by dhirajsb** [comment]
@zdtsw if we are going to support the default managementstate, then we should do it for all components. There is no explicit need to only support this for model registry. We should treat all components uniformly. 

@lburgazzoli wdyt?

**Comment by zdtsw** [comment]
> @zdtsw if we are going to support the default managementstate, then we should do it for all components. There is no explicit need to only support this for model registry. We should treat all components uniformly.
> 
> @lburgazzoli wdyt?

if the requirement is to get the change for all components (including the ones already out and the new ones e.g Modelreg etc) i am fine to have it on "component" 
the only thing i do no know is how UX will be for the upgrade case. esp. the components are already set to GA. 

one example for those who only use stable channel : if user first installed rhoai since 2.4, there is no CFO in that release. then upgrade to 2.8 CFO alread added as TP, then upgrade to 2.10 that CFO is GAed and then to 2.13. in theory, user should not see CFO in DSC at all. but with this "all component to removed" change, when they eventually upgrade to 2.16, they will see CFO as removed.  this could apply to other DW components too.

**Comment by dhirajsb** [comment]
We have already documented for RHOAI 2.14 that model registry component won't show up after an upgrade, similar to other ODH components. So, maybe it's best if we don't do this and preserve the current behavior. Especially since it seems to be more disruptive to all components.

**Comment by dhirajsb** [comment]
My recommendation is to not do this change, since it's going to cause more issues than solve anything at this point.

**Comment by zdtsw** [comment]
close this as the tracking jira issue is identified not a bug.
will have other ticket to dicuss what we would like for component to show as default later

**Pull request closed without merging**
