### PR TITLE
feat(codeflare): support unmanaged

### PR DESCRIPTION
**Pull request by zdtsw**
## Description
for the scope fo 1.35/2.4, since CFO will be on TP, we can keep the same logic of ODH operator 
and add more to handle "unmanaged" if it is needed in 2.5

- introduce new value of Unmanaged.
- old logic of handling "enable" is changed to match "managementState==Managed"
- set codeflare and ray by default as Unamaged when create default DSC instance

ref: https://github.com/opendatahub-io/opendatahub-operator/issues/600
depend on https://github.com/opendatahub-io/opendatahub-operator/pull/652

## new test
wait for rebase after https://github.com/opendatahub-io/opendatahub-operator/pull/652 to update

## old test
when set "codeflare" to Unmanaged, when others are either Managed or Removed
it does not block codeflare(no reconcile on missing CFO):
Screenshot from 2023-10-18 15-15-45

Screenshot from 2023-10-18 14-53-39
and it applied codeflare's manifests
Screenshot from 2023-10-18 14-54-34
and created imagestream 
Screenshot from 2023-10-18 15-14-03

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by VaishnaviHire** [comment]
When I uninstall the existing codeflare operator, and the state is set to `Managed` I see following error
```
    Component reconciliation failed: error during resmap resources:
        accumulating resources: accumulation err='accumulating resources from
        '../default': '/opt/manifests/codeflare/default' must resolve to a
        file': recursed accumulation of path '/opt/manifests/codeflare/default':
        accumulating resources: accumulation err='accumulating resources from
        '../crd': '/opt/manifests/codeflare/crd' must resolve to a file':
        recursed accumulation of path '/opt/manifests/codeflare/crd':
        accumulating resources: accumulation err='accumulating resources from
        'mcad': '/opt/manifests/codeflare/crd/mcad' must resolve to a file':
        recursed accumulation of path '/opt/manifests/codeflare/crd/mcad':
        accumulating resources: accumulation err='accumulating resources from
        'github.com/project-codeflare/multi-cluster-app-dispatcher/config/crd?ref=v0.0.0':
        evalsymlink failure on
        '/opt/manifests/codeflare/crd/mcad/github.com/project-codeflare/multi-cluster-app-dispatcher/config/crd?ref=v0.0.0'
        : lstat /opt/manifests/codeflare/crd/mcad/github.com: no such file or
        directory': no 'git' program on path: exec: "git": executable file not
        found in $PATH
```

**Comment by VaishnaviHire** [comment]
Should we include the changes for `unmanaged` support in separate PR, since those changes would not be included in the `main` branch

**Comment by zdtsw** [comment]
> When I uninstall the existing codeflare operator, and the state is set to `Managed` I see following error
> 
> ```
>     Component reconciliation failed: error during resmap resources:
>         accumulating resources: accumulation err='accumulating resources from
>         '../default': '/opt/manifests/codeflare/default' must resolve to a
>         file': recursed accumulation of path '/opt/manifests/codeflare/default':
>         accumulating resources: accumulation err='accumulating resources from
>         '../crd': '/opt/manifests/codeflare/crd' must resolve to a file':
>         recursed accumulation of path '/opt/manifests/codeflare/crd':
>         accumulating resources: accumulation err='accumulating resources from
>         'mcad': '/opt/manifests/codeflare/crd/mcad' must resolve to a file':
>         recursed accumulation of path '/opt/manifests/codeflare/crd/mcad':
>         accumulating resources: accumulation err='accumulating resources from
>         'github.com/project-codeflare/multi-cluster-app-dispatcher/config/crd?ref=v0.0.0':
>         evalsymlink failure on
>         '/opt/manifests/codeflare/crd/mcad/github.com/project-codeflare/multi-cluster-app-dispatcher/config/crd?ref=v0.0.0'
>         : lstat /opt/manifests/codeflare/crd/mcad/github.com: no such file or
>         directory': no 'git' program on path: exec: "git": executable file not
>         found in $PATH
> ```

i was talking to DW team yesterday, as they are still using 
github.com/project-codeflare/multi-cluster-app-dispatcher/config/crd?ref=v0.0.0
after manifests has been moved to the new CFO git repo, i will check with them again how they can change that

**Comment by zdtsw** [comment]
> Should we include the changes for `unmanaged` support in separate PR, since those changes would not be included in the `main` branch

good idea!
will have another one and leave this only for the CF manifests

**Comment by VaishnaviHire** [comment]
@zdtsw Are these changes still needed?

**Pull request closed without merging**
