### PR TITLE
[WIP]: support operator in restricted respectively airgapped network environments

### LINKED ISSUE #182: support operator in restricted / airgapped network environments
**Is your feature request related to a problem? Please describe.**
Airgapped and disconnected environments of Openshift and application software running on it typically work with mirror registries for containers. 

https://docs.openshift.com/container-platform/4.9/installing/installing-mirroring-installation-images.html 

They also work with custom catalogs for operators' OLM catalog sources: https://docs.openshift.com/container-platform/4.9/operators/admin/olm-managing-custom-catalogs.html

**Describe the solution you'd like**
Have the operator CSV defined in a way that respects ImageContentSourcePolicy (a kind of yaml with sort of softlinks to internal repos) and mirrored operator catalogs. Most important, image digest references instead of direct image tag references are critical. 

https://docs.openshift.com/container-platform/4.9/operators/admin/olm-restricted-networks.html#olm-mirror-catalog_olm-restricted-networks

This not only applies to OLM, but to deployment manifests with image section in general. Related in manifests: https://github.com/opendatahub-io/odh-manifests/issues/567

The two links above describe the context of the airgapped cluster. The necessary operator modifications are described here:

https://docs.openshift.com/container-platform/4.9/operators/operator_sdk/osdk-generating-csvs.html#olm-enabling-operator-for-restricted-network_osdk-generating-csvs

**Describe alternatives you've considered**
There are no alternatives (I use that statement carefully, as is often used in non-concensus-based) European politics ;-)

**Additional context**

### PR DESCRIPTION
**Pull request by shalberd**
fixes #182 
Airgapped and disconnected environments of Openshift and application software running on it typically work with mirror registries for containers.

https://docs.openshift.com/container-platform/4.9/installing/installing-mirroring-installation-images.html

They also work with custom catalogs for operators' OLM catalog sources: https://docs.openshift.com/container-platform/4.9/operators/admin/olm-managing-custom-catalogs.html

ImageContentSourcePolicy defined by the cluster admins in airgapped environments is honored by adding SHA digest references for images instead of references to image tags. 

## Description

Only to be done and integrated after latest Operator SDK has been merged in and tested.

https://docs.openshift.com/container-platform/4.9/operators/operator_sdk/osdk-generating-csvs.html#olm-enabling-operator-for-restricted-network_osdk-generating-csvs

or newer, OCP 4.10
https://docs.openshift.com/container-platform/4.10/operators/operator_sdk/osdk-generating-csvs.html#osdk-manually-defined-csv-fields_osdk-generating-csvs

relatedImages in CSV and digest-format ensure compatibility with OCP 4.9 airgapped and also work with 4.10 when mirroring images into a local registry, according to our cluster admin.

- CSV spec.relatedImages is filled out with image-key value referring to the digest of version 1.4.1 pull spec by digest as can be found out here: https://quay.io/repository/opendatahub/opendatahub-operator?tab=tags&tag=latest
- CSV metadata.annotations has a disconnected annotation, which indicates that the Operator works in a disconnected environment. As HTTP_PROXY and HTTPS_PROXY settings are honored as well when downloading manifests, we could extend this notation with proxy, too. 
`operators.openshift.io/infrastructure-features: '["disconnected", "proxy-aware"]'`
See example use cases at https://docs.openshift.com/container-platform/4.10/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-manual-annotations_osdk-generating-csvs
- CSV install.spec.deployments.image-key value referring to the digest of version 1.1.0 pull spec by digest

## How Has This Been Tested?
Will test this on an airgapped OCP 4.10 cluster with custom OLM catalog mirror and an auto-generated ImageContentSourcePolicy as a result of what comes with the operator CSV.
https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/4.5/html/preparing_to_deploy_in_a_disconnected_environment/creating-operator-imagecontentsourcepolicy_rhocs referencing the digest-format operator image at quai.io linking it to the local VMWare Harbor repo location. 

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by shalberd** [comment]
Important parts for this functionality:

https://github.com/opendatahub-io/opendatahub-operator/pull/183/files#diff-1b27681d7c325a954b7cf18f24fa0c9f6b6a8a8571611fd01252524fca96e4deR137

https://github.com/opendatahub-io/opendatahub-operator/pull/183/files#diff-1b27681d7c325a954b7cf18f24fa0c9f6b6a8a8571611fd01252524fca96e4deR143

https://github.com/opendatahub-io/opendatahub-operator/pull/183/files#diff-1b27681d7c325a954b7cf18f24fa0c9f6b6a8a8571611fd01252524fca96e4deR250

**Comment by Jooho** [comment]
For air-gapped installation, ODH needs to mirror many images to the local registry including odh-operator image. We are under development to support air-gapped installation and I hope we can support it by the end of this year.

**Comment by shalberd** [comment]
regarding relatedImages (List any related images, or other container images that your Operator might require to perform their functions):

@Jooho tested this on a broader level on a disconnected cluster for images that occur in odh-manifests and it works beautifully
quote:
_At this moment, we don't have a feature to pull all images with oc mirroring but we will add all image list into csv so all images specified in the CSV will be downloaded automatically._

If readability of yamls/deploymentconfigs/image references in digest format is a concern, you could also always add a yaml comment line showing the version tag above the image: line with the digest.

**Comment by shalberd** [comment]
> For air-gapped installation, ODH needs to mirror many images to the local registry including odh-operator image. We are under development to support air-gapped installation and I hope we can support it by the end of this year.

Under OCP 4.9, our cluster admin is already very successful doing this manually with oc adm catalog mirror and ImageContentSourcePolicy for a list of images for odh I gave him. https://docs.openshift.com/container-platform/4.9/installing/installing-mirroring-installation-images.html#olm-mirror-catalog_installing-mirroring-installation-images Seems that with 4.10 and 4.11, more developments are on the way, oc-mirror and so on. https://cloud.redhat.com/blog/mirroring-openshift-registries-the-easy-way. Whether your operator needs to support configuring the target docker repos, I don't know. But what it definetely needs to support is the digest, relatedImages part, as initially touched on here in this PR for only the operator image.

**Comment by shalberd** [comment]
For 4.9, relatedImages in the CSV remains the way to go for resolving images and honoring ImageContentSourcePolicy. For 4.10, there are changes coming, but those require the latest version of the operator-sdk, that @VaishnaviHire is working on in PR

**Comment by shalberd** [comment]
Here is how I am proceeding to get the SHA256 digests for relatedImages in the CSV. Source: v1.4.0 tarball of odh-manifests. 

```
 curl -o odh-manifests-tar.gz https://github.com/opendatahub-io/odh-manifests/tarball/v1.4.0
 tar -xvzf odh-manifests.tar.gz
 cd opendatahub-io-odh-manifests-bd8cfa9
```

Finding all image-tags of newer components, by newTag and newName
```
$ find . -type f -name "kustomization.yaml" -exec yq '.images | (filename, .)'  {} \; | grep -v '^null$';

./odh-notebook-controller/odh-notebook-controller/base/kustomization.yaml
- name: quay.io/opendatahub/odh-notebook-controller
  newName: quay.io/opendatahub/odh-notebook-controller
  newTag: master-bd77bfc
./odh-notebook-controller/kf-notebook-controller/overlays/openshift/kustomization.yaml
- name: public.ecr.aws/j1r0q0g6/notebooks/notebook-controller
  newName: quay.io/opendatahub/kubeflow-notebook-controller
  newTag: master-bd77bfc
./odh-notebook-controller/kf-notebook-controller/base/kustomization.yaml
- name: public.ecr.aws/j1r0q0g6/notebooks/notebook-controller
  newName: public.ecr.aws/j1r0q0g6/notebooks/notebook-controller
  newTag: v1.5.0
./ceph/object-storage/nano/base/kustomization.yaml
- name: ceph/daemon
  newTag: v0.7
  newName: quay.io/ceph/cn-core
- name: oc
  newName: quay.io/openshift/origin-cli
./data-science-pipelines/overlays/metadata-store-mariadb/kustomization.yaml
- name: mysql
  newName: registry.redhat.io/rhel8/mariadb-103
  newTag: "1-188"
./data-science-pipelines/overlays/object-store-minio/kustomization.yaml
- name: minio
  newName: quay.io/opendatahub/minio
  newTag: RELEASE.2019-08-14T20-37-41Z-license-compliance
./data-science-pipelines/overlays/component-mlmd/kustomization.yaml
- name: metadata-envoy
  newName: gcr.io/ml-pipeline/metadata-envoy
  newTag: 1.7.0
- name: metadata-grpc
  newName: gcr.io/tfx-oss-public/ml_metadata_store_server
  newTag: 1.0.0
- name: metadata-writer
  newName: quay.io/internaldatahub/metadata-writer
  newTag: 1.1.0
./data-science-pipelines/overlays/metadata-store-mysql/kustomization.yaml
- name: mysql
  newName: gcr.io/ml-pipeline/mysql
  newTag: "5.7"
./data-science-pipelines/overlays/metadata-store-postgresql/kustomization.yaml
- name: postgresql
  newName: quay.io/internaldatahub/postgresql-96-centos7
  newTag: "9.6"
./data-science-pipelines/overlays/ds-pipeline-ui/kustomization.yaml
- name: frontend
  newName: quay.io/internaldatahub/frontend
  newTag: 1.1.0
./data-science-pipelines/base/kustomization.yaml
- name: persistenceagent
  newName: quay.io/internaldatahub/persistenceagent
  newTag: 1.1.0
- name: scheduledworkflow
  newName: quay.io/internaldatahub/scheduledworkflow
  newTag: 1.1.0
- name: viewer-crd-controller
  newName: gcr.io/ml-pipeline/viewer-crd-controller
  newTag: 1.7.0
- name: visualization-server
  newName: gcr.io/ml-pipeline/visualization-server
  newTag: 1.7.0
- name: api-server
  newName: quay.io/internaldatahub/api-server
  newTag: 1.1.0
./model-mesh/overlays/odh-model-controller/manager/kustomization.yaml
- name: controller
  newName: quay.io/opendatahub/odh-model-controller
  newTag: nomeshsupport-0.9.0
./model-mesh/runtimes/kustomization.yaml
- name: tritonserver-2
  newName: nvcr.io/nvidia/tritonserver
  newTag: 21.06.1-py3
- name: mlserver-0
  newName: quay.io/opendatahub/mlserver
  newTag: 0.5.2
- name: ovms-1
  newName: openvino/model_server
  newTag: "2022.1"
./model-mesh/manager/kustomization.yaml
- name: modelmesh-controller
  newName: quay.io/opendatahub/modelmesh-controller
  ## NOTE THIS SHOULD BE REPLACED WITH LATEST CONTROLLER IMAGE TAG
  newTag: v0.9.0-secretpatch
./doh-dashboard/overlays/authentication/kustomization.yaml
- name: oauth-proxy
  newName: registry.redhat.io/openshift4/ose-oauth-proxy
  newTag: v4.8 --> using 4.10 instead to get sha256 hash
./odh-dashboard/base/kustomization.yaml
- name: odh-dashboard
  newName: quay.io/opendatahub/odh-dashboard
  newTag: v2.2.1
```

for offline use with mirroring, spec.tags.from.name in ImageStreams need to be in digest-format, too, e.g. here https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/notebook-images/overlays/additional/elyra-notebook-imagestream.yaml#L21

```
 $ find . -type f  -name "*imagestream*" -exec yq '.spec.tags[].from.name | (filename, .)'  {} \; ;
./jupyterhub/notebook-images/overlays/additional/tensorflow-notebook-imagestream.yaml
quay.io/thoth-station/s2i-tensorflow-notebook:v0.0.2
./jupyterhub/notebook-images/overlays/additional/minimal-notebook-imagestream.yaml
./jupyterhub/notebook-images/overlays/additional/minimal-notebook-imagestream.yaml
quay.io/thoth-station/s2i-minimal-py38-notebook:v0.3.0
quay.io/thoth-station/s2i-minimal-notebook:v0.3.0
./jupyterhub/notebook-images/overlays/additional/elyra-notebook-imagestream.yaml
quay.io/thoth-station/s2i-lab-elyra:v0.1.5
./jupyterhub/notebook-images/overlays/additional/generic-data-science-notebook-imagestream.yaml
quay.io/thoth-station/s2i-generic-data-science-notebook:v0.0.5
./jupyterhub/notebook-images/base/nbviewer-imagestream.yaml
quay.io/odh-jupyterhub/nbviewer:latest
./jupyterhub/notebook-images/base/spark-notebook-imagestream.yaml
quay.io/odh-jupyterhub/s2i-spark-minimal-notebook:py36-spark2.4.5-hadoop2.7.3
```

Jupyterhub images non-Imagestream
```
$ cd jupyterhub/jupyterhub/
$ grep -rnw . -e "image:"
./overlays/jupyterhub-idle-culler/deploymentconfig.yaml:16:          image: 'quay.io/odh-jupyterhub/jupyterhub-img:v0.3.3'
./overlays/jupyterhub-idle-culler/deploymentconfig.yaml:33:          image: quay.io/odh-jupyterhub/jupyterhub-img:v0.3.5
./base/traefik-deployment.yaml:44:        image: "registry.access.redhat.com/ubi8/ubi-micro:8.4"
./base/traefik-deployment.yaml:64:      - image: quay.io/internaldatahub/traefik:v1.7-build
./base/traefik-deployment.yaml:102:      - image: quay.io/internaldatahub/configmap-puller:0.1
./base/jupyterhub-db-dc.yaml:26:      - image: registry.redhat.io/rhel8/postgresql-96
./base/jupyterhub-dc.yaml:20:      image: quay.io/openshift/origin-deployer:4.7.0
./base/jupyterhub-dc.yaml:157:        image: quay.io/odh-jupyterhub/jupyterhub-img:v0.3.8
./base/jupyterhub-dc.yaml:194:        image: 'quay.io/opendatahub/leader-elector:v0.1'
./base/jupyterhub-dc.yaml:239:        image: quay.io/odh-jupyterhub/jupyterhub-img:v0.3.8
```
Coupled with docker inspect for getting the digest without downloading all the images, e.g. 

`docker inspect --format='{{index .RepoDigests 0}}' <repoimagepath:tag>`

or similar, you know [what I mean](https://stackoverflow.com/questions/39375421/can-i-get-an-image-digest-without-downloading-the-image)

**Comment by VaishnaviHire** [comment]
Need to make separate PR for v2 operator

**Pull request closed without merging**
