### PR TITLE
doc: correct godoc

### PR DESCRIPTION
**Pull request by zdtsw**
## Description

to follow up discussion https://github.com/opendatahub-io/opendatahub-operator/pull/1145#discussion_r1700136942
By reading upgrade document, my understanding is, the code logic is correct but the comments did not get updated.

## Merge criteria

- [ ] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [ ] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [ ] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by ykaliuta** [comment]
It will make conflict in #1145 I added removing of the line there

**Comment by zdtsw** [comment]
> It will make conflict in #1145 I added removing of the line there

i can make this as a draft , just need @VaishnaviHire to double confirm it is the right logic, then i can close this PR or you can cherry pick it to 1145 if you want.

**Comment by ykaliuta** [comment]
> > It will make conflict in #1145 I added removing of the line there
> 
> i can make this as a draft , just need @VaishnaviHire to double confirm it is the right logic, then i can close this PR or you can cherry pick it to 1145 if you want.

Let me remove it from #1145 then. It is been outdated for a while already and is not related directly to the PR

**Review by VaishnaviHire — APPROVED** [review]
/lgtm

**Pull request merged**
