### PR TITLE
feat: pass platform from env variable or fall back to use old logic

### PR DESCRIPTION
**Pull request by zdtsw**
## Description

feat: pass platform from env variables or fall back to use old logic
    
    - introduce new env var ODH_PLATFORM_TYPE, value set during build time
      - if value not match, fall back to detect managed then self-managed
 ~~introduce new env var OPERATOR_RELEASE_VERSION, value also set during build time~~
 ~~if value is empty, fall back to use old way from CSV to read version or use 0.0.0~~
 ~~add support from makefile~~
 ~~use envstubst to replace version~~
(split from https://github.com/opendatahub-io/opendatahub-operator/pull/1231)

## Merge criteria

- [ ] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [ ] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [ ] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by ykaliuta** [comment]
I support the change. And it is backward compatible. Just worried about the formal process now.

**Comment by zdtsw** [comment]
i can markt it to [draft] for now and wait to see how / when we want it

**Comment by ykaliuta** [comment]
> I support the change. And it is backward compatible. Just worried about the formal process now.

It was about original version where only platform was passed with environment.
Version is a different piece of information and I do not support using environment for that (it was already discussed in some other PR)

**Comment by zdtsw** [comment]
> > I support the change. And it is backward compatible. Just worried about the formal process now.
> 
> It was about original version where only platform was passed with environment. Version is a different piece of information and I do not support using environment for that (it was already discussed in some other PR)

i do not tend to get the version part out, but to run the full tests, i will need to get it from draft to PR to trigger ci.
for the "it was already discussed in some other PR", maybe i missed/dont recall that part , do you have a reference where the converstation ended?

**Comment by ykaliuta** [comment]
> i do not tend to get the version part out, but to run the full tests, i will need to get it from draft to PR to trigger ci. for the "it was already discussed in some other PR", maybe i missed/dont recall that part , do you have a reference where the converstation ended?

Jira (13115) and probably slack actually. Looks like was ignored.

**Comment by zdtsw** [comment]
> > i do not tend to get the version part out, but to run the full tests, i will need to get it from draft to PR to trigger ci. for the "it was already discussed in some other PR", maybe i missed/dont recall that part , do you have a reference where the converstation ended?
> 
> Jira (13115) and probably slack actually. Looks like was ignored.

i removed the part for the release version

**Review by ykaliuta — APPROVED** [review]

**Pull request merged**
