### PR TITLE
DSCI CRD: allow default as a value for logmode

### PR DESCRIPTION
**Pull request by ykaliuta**
default is a separate mode in the sources, not just selection of one of the others, so allow it explicitly.

There is no difference if it is set to "" explicitly or not set since "" is a string default value.

In the current code as soon as devFlags are present, the mode is taken in use, so it is reset to default even if it is not set which does not look right (I would expect leave it untouched if is not set). If it is fixed, then it will be impossible to reset logging mode to default from devel or prod: if "" is considered as "not set explicitly", then there is no value for default, the object checker rejects values not in list.

## Merge criteria

- [ ] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [ ] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [ ] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by zdtsw** [comment]
i am fine with this change.
but try to understand the case better:
in DSCI under devFlags we currently have 
1. logmode
2. manifestsUri => this should have been set to deprecated (https://github.com/opendatahub-io/opendatahub-operator/pull/1137)
I understand : " In the current code as soon as devFlags are present, the mode is taken in use" as
```
spec:
  devFlags:
    logmode: ""
    manifestsUri:  ....
```
 is the same as 
```
spec:
  applicationsNamespace: opendatahub
  devFlags:
       manifestsUri:  ....
```
because "" is the default value for string


but since we do not use   manifestsUri
so it can only be done explictiliy as 
```
spec:
  devFlags:
    logmode: ""
```
not 
```
spec:
  devFlags:
```
(as this will remove the whole devFlags) 

is this the concern for the PR?

**Comment by ykaliuta** [comment]
> is this the concern for the PR?

May be not exactly. The point is as soon as devFlags present, logmode is considered to be set to "" even if it is not. I actually had in mind scenario where a "user" sets just manifests (ok, deprecated now, but anyway) and automatically resets the logmode.

**Comment by ykaliuta** [comment]
> > is this the concern for the PR?
> 
> May be not exactly. The point is as soon as devFlags present, logmode is considered to be set to "" even if it is not. I actually had in mind scenario where a "user" sets just manifests (ok, deprecated now, but anyway) and automatically resets the logmode.

And if it fixed (I can only fix it with ignoring of ""), there is no way to force default anymore

**Comment by zdtsw** [comment]
> > is this the concern for the PR?
> 
> May be not exactly. The point is as soon as devFlags present, logmode is considered to be set to "" even if it is not. I actually had in mind scenario where a "user" sets just manifests (ok, deprecated now, but anyway) and automatically resets the logmode.

yep, so if the user want to set logmode to $value or "" i dont think it could be a case that we have  devFlags without logmode there.
but yeah, as i said, i dont see problem with having a value default defined there.

**Comment by ykaliuta** [comment]
> i dont think it could be a case that we have devFlags without logmode there

Yep. That is the hypothetical case I'm addressing

**Review by zdtsw — APPROVED** [review]
would like to have 2nd eyes on this as well

**Pull request merged**
