### PR TITLE
ODH 1.4.1 openshift system and additional CAs bundle from configmap used for golang SSL trust store

### PR DESCRIPTION
**Pull request by shalberd**
Key motivation: downloading manifest tar.gzs, for example, but not limited to, custom ones, from an airgapped environment enterprise-internal server location. Even if not airgapped, not having resources downloaded from a public location is common practice. Internal infrastructure such as Artifactory, Nexus, and so on usually does not have publicly-trusted certificates. Leaving the cool, cutting-edge stuff to you guys at ODH and making sure such issues are covered ;-)

Do not merge this PR before 1.4.1 CRDs / manifests are merged via https://github.com/opendatahub-io/opendatahub-operator/pull/188/files

Background OCP / Openshift central

https://docs.openshift.com/container-platform/4.8/networking/configuring-a-custom-pki.html#installation-configure-proxy_configuring-a-custom-pki

key concept: additionalTrustBundle PEM-Format files

Configmap with label config.openshift.io/inject-trusted-cabundle: "true" provides a block of PEM Format CA files with configmap data section key

ca-bundle.crt 

containing the user-provided (additionalTrustBundle e.g. from [private PKI](https://www.techtarget.com/searchsecurity/definition/private-CA-private-PKI)) and publicly-trusted system CA certificates in a single bundle file.

For downloading manifests tar files using HTTPS, the operator uses go-getter from hashicorp for url parsing, and golang net/http &http.Transport, which in turn uses client get and system settings from golang net/http.

**Important assumption: I am assuming the cryto/X509 context is implicit when using golang http client functionality. That is, that x509.SystemCertPool is used. Update 20 October: The assumption holds, that is, the env variable SSL_CERT_FILE is honored by golang and SSL trust is established, enabling manifest download.**

After discussion with the RHOSDS team, we have decided it is not necessary to use an additional env variable.

Also, the mounted volume can be defined in the subscription CRD instead of the deployment CRD.

https://docs.openshift.com/container-platform/4.10/operators/admin/olm-configuring-proxy-support.html#olm-inject-custom-ca_olm-configuring-proxy-support

Golang has standard locations from which it loads certificates for SSL CA Trust, in this case for rhel, that directory is /etc/pki/tls/certs

https://github.com/golang/go/blob/e83bcd95a4a86e4caf2faa78158170d512dd9de5/src/crypto/x509/root_unix.go#L20

Operator has the following OS version RHEL and name as base system Docker:

```
cat /etc/os-release

ID="rhel"
VERSION_ID="8.5"
```

## Description

- Added a configmap to the overlay that provides ca-bundle.crt from openshift central config, containing both system-level CAs as well as additonal CAs, e.g. from a private PKI. Having those CAs as trusted by golang is immensely important in environments that rely on private PKI for any internal serving software, e.g. Artifactory, Nexus, Harbor, and many more.

- Before this PR,  if a user had his or her manifests .tar files stored in an URL location that is using server certificates based on private PKI, an SSL validation error occurs and a message "couldn't download URI appears in the log".

- To remedy this, we mount the file containing the CA-bundle from the new configmap into a volume of the opendatahub-operator container at /etc/pki/ca-trust/extracted/pem. We do not do this in the context of the operator bundle, but the subscription object. https://github.com/opendatahub-io/opendatahub-operator/pull/173#issuecomment-1308859374

grafik

## How Has This Been Tested?
I modified subscription CRD to overwrite the standard softlink target /etc/pki/tls/certs, which points to  /etc/pki/ca-trust/extracted/pem.

I created the auto-inject configmap manually on openshift-operators namespace, but we can deliver it with the operator manifests in future, as part of this PR 

I tested download from an internal url (Artifactory) that is secured by a non-publicly-trusted-CA-based SSL certificate.
Download worked beautifully. 

Even if the cluster proxy object is empty and no additional trusted certificates are defined centrally, the cluster network operator still provides a current list of CAs from the Core OS that is underlying Openshift. So, in any case, we have a much more up-to-date list of CAs in the default location for golang trust, plus, optionally, also additonal trusted CAs that cluster admins defined.

**Update November 2022 regarding functionality test on disconnected system with manifest tar gz on server with SSL certificate based on private PKI-based CA:**

Tested in detail, works very nicely. https://github.com/opendatahub-io/opendatahub-operator/pull/173#issuecomment-1308859374

I would suggest I also add some documentation on this for the public website. 

https://github.com/opendatahub-io/opendatahub.io/pull/48

See 
## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by LaVLaS** [comment]
@shalberd Can you copy this to a dedicated overlay specifically for this feature. At this time, we want to keep these changes separate from the opendatahub manifest until the time that we can provide official support for this deployment method

**Comment by shalberd** [comment]
@LaVLaS How is the opendatahub-operator image built? If these changes were moved to a separate overlay, how would the operator including image be deployed then?

**Comment by VaishnaviHire** [comment]
I tested this with latest operator image, the configmap was deployed successfully

**Comment by LaVLaS** [comment]
Thx @VaishnaviHire for the review

@shalberd Your PR is greatly appreciated as this adds developer support for pulling manifests from authenticated urls

```
If these changes were moved to a separate overlay, how would the operator including image be deployed then? 
```
These manifests are for a manual deploy of the opendatahub-operator using kustomize.  Deploying this from an overlay would just consist of specifying a different directory for the overlays `kustomization.yaml`

```
What is the relationship between this repo, opendatahub-operator. and the odh-manifests repo that I think @LaVLaS is talking about here? The idea here is to enable the opendatahub-operator pod/container in openshift-operators to include custom CA trust mounted in at /etc/pki/tls/additional in addition to trusting the CAs as defined on a system level by default in the Red Hat Enterprise Linux base docker image at /etc/pki/tls/certs.
```
From a technical perspective there is, currently, a loose relationship between opendatahub-operator and odh-manifests as the operator is just responsible for the download of all of the manifest tarballs defined  `.spec.repos[].uri` of the kfdef.  odh-manifests is just the fully supported manifests for deploying ODH Core components.

Logically they are directly linked since the future development of the operator will officially break from the deprecated kfctl operator and we will be rewriting the code to support features required for managing the full lifecycle ODH Core deployments.

For this PR, we will just confirm that it does not break existing functionality when deployed manually using `kustomize build kustomize/overlays/opendatahub` until we start the on-prem Working Group to provide official community guidance and support for deploying ODH Core in disconnected environments

**Comment by shalberd** [comment]
@LaVLaS 
```
 Your PR is greatly appreciated as this adds developer support for pulling manifests from authenticated urls
```

Actually, no, it adds developer support for pulling manifests from https url locations that have server certificates that are backed by custom CAs. Those system-level and private PKI CAs have in themselves nothing to do with airgapped, as even on a cluster open to the Internet, we could have a company-internal server with an SSL chain of trust based on custom CAs from that said private PKI.

The pull request in its description via links acknowledges that in the golang code of the operator, the http proxy settings are already honored. I have not found a place in the operator code where http basic authentication with username and api key is supported for the secured download via https of manifest tarballs defined via `.spec.repos[].uri` of the kfdef. odh-manifests. What matters is that with the changes in this PR, tarballs hosted on an internal server with a non-publicly-trusted SSL certificate are made possible.

To enable trust for all SSL certificates auto-injected by the cluster into the configmap, that location including filename

`etc/pki/tls/additional/trustedcas.pem`

, mounted into the container, is defined in the golang environment variable SSL_CERT_FILE, which since 2017 is an additional way of providing additional system root trust store certificates. The system root trust store for RHEL 8 is still added by golang, in that OS base image RHEL 8 case from /etc/pki/tls/certs. See the golang code links in the main PR description.

How is the operator package bundle built and could that include the configmap and modifications to the opendatahub-operator Deployment object as well in the namespace openshift-operators?

For version 1.4, will you still have this controllers / kfctl operator-based opendatahub-operator? If yes, could you integrate these changes (configmap, volume for bundle file and volumemount at a location in container, env variable SSL_CERT_FILE, to the packaged operator that is deployed via subscription as well?

For us as a provider in the financial services industry, that internal infrastructure, be it disconnected or not, is always present and always has non-publicly-trusted server certificates. Thus, if I want to host my own manifests with changes like custom docker repos locations (internal ones), I currently have no way to do so internally, as the SSL chain of trust breaks and Url download error appears.

For context: Why do I have the 1.2 manifests running at all? That was a one-time deal to get the components running at all, allowing download from the public internet. That avenue is now closed and I have to place my tarball in our internal Artifactory or Nexus server location.

**Comment by shalberd** [comment]
@LaVLaS i.e.

- adding the configmap to 1.4.0/manifests/trusted-cabundle_v1_configmap.yaml

- adding the volume, volumeMount, and env variable to the deployments template spec at 1.4.0/manifests/opendatahub-operator.v1.4.0.clusterserviceversion.yaml

**Comment by LaVLaS** [comment]
/retest

@shalberd We won't be able to include this in the 1.4.0 OperatorHub release but we will look into including this for the next v1.4.1 operator release.  ODH is long overdue for providing official guidance for disconnected deployments and we need to start start setting up a reproducible disconnected environment to officially verify functionality

**Comment by shalberd** [comment]
OK, I did not test the manual install via kustomize, but modified the Open Data Hub Operator ClusterServiceVersion object yaml on our disconnected cluster. The configmap trusted-cabundle containing the auto-injected trusted CAs bundle with key ca-bundle.crt is present in namespace openshift-operators as well.

Project openshift-operators 
Operators - Installed Operators - Open Data Hub Operator

yaml section

Bildschirmfoto 2022-10-18 um 15 01 24

new content (excerpt):

```
spec:
                containers:
                  - command:
                      - opendatahub-operator
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: 'metadata.annotations[''olm.targetNamespaces'']'
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        value: opendatahub-operator
                      - name: SSL_CERT_FILE
                        value: /etc/pki/tls/additional/trustedcas.pem
                    image: 'quay.io/opendatahub/opendatahub-operator:v1.2.0'
                    imagePullPolicy: Always
                    name: opendatahub-operator
                    resources: {}
                    volumeMounts:
                      - mountPath: /etc/pki/tls/additional
                        name: trusted-cabundle-volume
                        readOnly: true
                serviceAccountName: opendatahub-operator
                volumes:
                  - configMap:
                      items:
                        - key: ca-bundle.crt
                          path: trustedcas.pem
                      name: trusted-cabundle
                      optional: true
                    name: trusted-cabundle-volume
    strategy: deployment
```

After that, the opendatahub-operator pod restarted in namespace openshift-operators and was reconfigured as intended:

Bildschirmfoto 2022-10-18 um 15 15 46

Bildschirmfoto 2022-10-18 um 15 18 16

Looking into the container opendatahub-operator, the env var and new mount location /etc/pki/tls/additional including the file containing all CAs (system- and additional, e.g. from private PKI) at cluster-level are acccessible. The default location at /etc/pki/certs is also still there.

```
sh-4.4$ cd /etc/pki/tls
sh-4.4$ ls
additional  cert.pem  certs  ct_log_list.cnf  misc  openssl.cnf  private
sh-4.4$ ls -all
total 16
drwxr-xr-x. 1 root root    24 Oct 18 10:41 .
drwxr-xr-x. 1 root root    17 Mar 28  2022 ..
drwxrwxrwx. 3 root root    82 Oct 18 10:41 additional
lrwxrwxrwx. 1 root root    49 Jun 16  2021 cert.pem -> /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
drwxr-xr-x. 2 root root    54 Mar 28  2022 certs
-rw-r--r--. 1 root root   412 Mar 23  2022 ct_log_list.cnf
drwxr-xr-x. 2 root root     6 Mar 23  2022 misc
-rw-r--r--. 1 root root 11227 Mar 23  2022 openssl.cnf
drwxr-xr-x. 2 root root     6 Mar 23  2022 private
sh-4.4$ cd certs
sh-4.4$ ls -all
total 0
drwxr-xr-x. 2 root root 54 Mar 28  2022 .
drwxr-xr-x. 1 root root 24 Oct 18 10:41 ..
lrwxrwxrwx. 1 root root 49 Jun 16  2021 ca-bundle.crt -> /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
lrwxrwxrwx. 1 root root 55 Jun 16  2021 ca-bundle.trust.crt -> /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
sh-4.4$ cd ..
sh-4.4$ cd additional
sh-4.4$ pwd   
/etc/pki/tls/additional
sh-4.4$ ls -all
total 0
drwxrwxrwx. 3 root root 82 Oct 18 10:41 .
drwxr-xr-x. 1 root root 24 Oct 18 10:41 ..
drwxr-xr-x. 2 root root 28 Oct 18 10:41 ..2022_10_18_10_41_51.2590702234
lrwxrwxrwx. 1 root root 32 Oct 18 10:41 ..data -> ..2022_10_18_10_41_51.2590702234
lrwxrwxrwx. 1 root root 21 Oct 18 10:41 trustedcas.pem -> ..data/trustedcas.pem
sh-4.4$ env | grep CERT
SSL_CERT_FILE=/etc/pki/tls/additional/trustedcas.pem
sh-4.4$ 
sh-4.4$ grep Amazon trustedcas.pem 
# Amazon Root CA 1
# Amazon Root CA 2
# Amazon Root CA 3
# Amazon Root CA 4
sh-4.4$ grep Digi  trustedcas.pem 
# DigiCert Assured ID Root CA
sh-4.4$ grep -o -i "end certificate" trustedcas.pem | wc -l
132
sh-4.4$ grep -o -i "begin certificate" trustedcas.pem | wc -l
132
sh-4.4$ 
```

That is all nice and dandy, but does the new SSL_CERT_FILE env variable now have an impact when defined a new url download location on a server that has a certificate based on custom CAs?

I tested this the following way:

old KfDef file repos section in namespace odhsven:

``` 
  repos:
    - name: kf-manifests
      uri: https://github.com/opendatahub-io/manifests/tarball/v1.4.0-rc.2-openshift
    - name: manifests
      uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/v1.2'
```

modified KfDef so point my manifests location to the internal server with custom CA-based SSL certificate.
```
  repos:
    - name: kf-manifests
      uri: https://github.com/opendatahub-io/manifests/tarball/v1.4.0-rc.2-openshift
    - name: manifests
      uri: 'https://repo.internaldomain.ch/artifactory/i_datascience_intern/opendatahub-io-odh-manifests-v1.2.0-0-gdcee3f6.tar.gz'
```

deleted /tmp/odhsven/opendatahub/.cache directory in opendatahub-operator container

restarted opendatahub-operator container

result:

correct download of manifests from internal location, ssl chain trust ok, no more Url Download errors! Fetch successed.
So, the env variable SSL_CERT_FILE, containing, among others, the root and intermediate CA of the private PKI, leads to trust finally being established.

```
sh-4.4$ pwd
/tmp/odhsven/opendatahub/.cache/manifests
sh-4.4$ 
time="2022-10-18T12:46:41Z" level=info msg="Reconciling KfDef resources. Request.Namespace: odhsven, Request.Name: opendatahub."
time="2022-10-18T12:46:41Z" level=info msg="Creating a new KubeFlow Deployment. KubeFlow.Namespace: odhsven."
time="2022-10-18T12:46:42Z" level=info msg="Creating directory /tmp/odhsven/opendatahub/.cache"
time="2022-10-18T12:46:45Z" level=info msg="Fetching https://repo.internaldomain.ch/artifactory/i_datascience_intern/opendatahub-io-odh-manifests-v1.2.0-0-gdcee3f6.tar.gz to /tmp/odhsven/opendatahub/.cache/manifests"
time="2022-10-18T12:46:45Z" level=info msg="Updating localPath to /tmp/odhsven/opendatahub/.cache/manifests/opendatahub-io-odh-manifests-dcee3f6"
time="2022-10-18T12:46:45Z" level=info msg="Fetch succeeded; LocalPath /tmp/odhsven/opendatahub/.cache/manifests/opendatahub-io-odh-manifests-dcee3f6"
```

**Comment by Jooho** [comment]
@shalberd  Have you tried this way to set a custom certificate to the operator? This can inject a certificate into the operator by OpenShift Subscription object. 
https://docs.openshift.com/container-platform/4.11/operators/admin/olm-configuring-proxy-support.html#olm-overriding-proxy-settings_olm-configuring-proxy-support

**Comment by Jooho** [comment]
@shalberd Thanks for your detailed test. ConfigMap is mandatory so it must be created before creating a subscription.
This is kind of manual way so I also like adding some objects to support a custom certificate by the operator.  However,  I think we need to consider SSL Proxy Server as well. Regarding the SSL Proxy Server, we need to add environmental variables when the cluster set Proxy information using Proxy Object. Definitely, the custom certificate for the proxy server is needed to apply as well.

**Comment by shalberd** [comment]
> Regarding the SSL Proxy Server, we need to add environmental variables when the cluster set Proxy information using Proxy Object. Definitely, the custom certificate bundle for the proxy server is needed to apply as well.

You just have to configure it centrally in the proxy spec field. 

https://docs.openshift.com/container-platform/4.10/networking/configuring-a-custom-pki.html#nw-proxy-configure-object_configuring-a-custom-pki

You do not have to override them/set them explicitely in the subsciption. Thus, the proxy server information is already there in the container envs, it is automatically applied from the central proxy config. See the proxy envs in our case, not specifically overridden via subscription spec, **already there**

Container proxy envs are automatically present in operator container:

```
sh-4.4$ env | grep PROXY
HTTP_PROXY=http://server-proxy.xxx.xxx.ch:8080
HTTPS_PROXY=http://server-proxy.xxx.xxx.ch:8080
NO_PROXY=.cluster.local,.ocp4dev.xxx.ch,.myserver.ch
```

What is great that the additonal CAs were honored even though my internal artifactory server is listed in the DNS zone NO_PROXY.

"Definitely, the custom certificate bundle for the proxy server is needed to apply as well.":

Yes, you either define that at cluster install time or afterwards, create that configmap user-ca-bundle in namespace openshift-config, correct. The reference the configmap at spec.trustedCA.name of the cluster proxy object.

Hope that all makes sense.

**Comment by shalberd** [comment]
@LaVLaS please see my testing and comments on the topic of downloading manifests from a server-url-location that is using a private PKI based certificate. The cluster network operator provides a mix-in of both openshift core OS publicly-trusted CAs as well as additional trusted CAs. The idea is to deliver this via a configmap. I have tested this in https://github.com/opendatahub-io/opendatahub-operator/pull/173#issuecomment-1308892304 and it can go into 1.4.1. Also, for context and easier finding out by potential enterprise users, see my added [documentation PR](https://github.com/opendatahub-io/opendatahub.io/pull/48)

**Pull request closed without merging**
