### PR TITLE
chore: uplift kustomize version for match the one from kyaml

### PR DESCRIPTION
**Pull request by zdtsw**
- this kustomize is internal used for Operator to generate manifests and bundle
- this would help if we want to local debug component manifests since some are already generated by v5
- it does not mean we have converted all component manifests to v5 for Operator image to run with

## Merge criteria

- [ ] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [ ] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [ ] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by ykaliuta** [comment]
Probably autogenerated webhook kustomization should be adjusted as well,
```
diff --git a/config/webhook/kustomizeconfig.yaml b/config/webhook/kustomizeconfig.yaml
deleted file mode 100644
index 25e21e3c963f..000000000000
--- a/config/webhook/kustomizeconfig.yaml
+++ /dev/null
@@ -1,25 +0,0 @@
-# the following config is for teaching kustomize where to look at when substituting vars.
-# It requires kustomize v2.1.0 or newer to work properly.
-nameReference:
-- kind: Service
-  version: v1
-  fieldSpecs:
-  - kind: MutatingWebhookConfiguration
-    group: admissionregistration.k8s.io
-    path: webhooks/clientConfig/service/name
-  - kind: ValidatingWebhookConfiguration
-    group: admissionregistration.k8s.io
-    path: webhooks/clientConfig/service/name
-
-namespace:
-- kind: MutatingWebhookConfiguration
-  group: admissionregistration.k8s.io
-  path: webhooks/clientConfig/service/namespace
-  create: true
-- kind: ValidatingWebhookConfiguration
-  group: admissionregistration.k8s.io
-  path: webhooks/clientConfig/service/namespace
-  create: true
-
-varReference:
-- path: metadata/annotations
```

**Comment by ykaliuta** [comment]
BTW, wondering how namespace and name works without it

**Comment by zdtsw** [comment]
> diff --git a/config/webhook/kustomizeconfig.yaml b/config/webhook/kustomizeconfig.yaml

not sure i understand this "diff" part:  where the changes come from?

**Comment by ykaliuta** [comment]
> > diff --git a/config/webhook/kustomizeconfig.yaml b/config/webhook/kustomizeconfig.yaml
> 
> not sure i understand this "diff" part: where the changes come from?

I removed the file and run git diff. But may be just `varReference`, since it is related to obsoleted `vars` should be removed. About nameReference and namespace I should check more carefully.

**Comment by ykaliuta** [comment]
Let's do it separately

**Review by ykaliuta — APPROVED** [review]

**Pull request merged**
