### PR TITLE
Makefile: generate config/manager/kustomization.yaml

### PR DESCRIPTION
**Pull request by ykaliuta**
There is a modification, `kustomize edit` of this file on deploy and bundle targets. Since the file is stored in the version control it pollutes `git status` and `git commit -a`.

Store only "template" in the VCS and generate the file at the build time.

Move it to a separate target to not repeat yourself.

It will check the target for more other targets than before, but it should not make any harm.

Make it phony to generate the file every time for the case of changing IMG variable.

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by VaishnaviHire — APPROVED** [review]
/lgtm

**Comment by bartoszmajsak** [comment]
We missed adding `kustomize.yaml` to `.gitignore`. Without this, we solved the problem of polluting repo only halfway. 

I was wondering if we could improve this solution and not rely on temporary `yaml.in` file. I would suggest having a structure of manifests so that I can simply apply them using kustomize without any `Makefile` prereqs and it would work. So following "Principle of least surprise" how about using  reasonable default such as `quay.io/opendatahub.io/opendatahub-operator` instead of using non-existing `REPLACE_IMAGE`.  Then ` $(KUSTOMIZE) edit set image controller=$(IMG)` would be enough and I can actually source the manifests from here. To solve the problem of polluting the repo with overwritten values I can think of two ways:

- create and share `.githooks` to prevent from accidentally committing wrong files. Such a hook (pre-commit?) can just reset the file to desired state
- do the same as with the git-hook, but as GH Action

Second option does not require any contributor to set up git in a certain way. It will just work.

WDYT @ykaliuta @VaishnaviHire?

**Comment by ykaliuta** [comment]
> We missed adding `kustomize.yaml` to `.gitignore`. Without this, we solved the problem of polluting repo only halfway. Now after running make targets I end up with:
> 
> ```
> Untracked files:
>   (use "git add <file>..." to include in what will be committed)
>         config/manager/kustomization.yaml
> ```
> 
> so `git commit -a` would make the issue re-appear again.

No, untracked files does not break `git commit -a` and is a least problem. But I agree, adding it to .gitignore is a right thing to do.

I should notice that now another change was committed which regenenerates config/rbac/role.yaml (which should have been committed with the change). And `make bundle` has the same problem which I missed at the time. 

OR all the generated manifests should not be commited at all and generated with `make manifests` (by dependency probably) on demand (not related to image name issue).

So, there should be followup unfortunately anyway.

> 
> I was wondering if we could improve this solution and not rely on temporary `yaml.in` file. I would suggest having a structure of manifests so that I can simply apply them using kustomize without any `Makefile` prereqs and it would work.
> 
> So following "Principle of least surprise" how about using reasonable default such as `quay.io/opendatahub.io/opendatahub-operator` instead of using non-existing `REPLACE_IMAGE`. Then ` $(KUSTOMIZE) edit set image controller=$(IMG)` would be enough to `make deploy` your image. No need for special temporary file, which might not be obvious for ppl knowing kustomize, but not our special way of handling it.

So for `make deploy` you should have a manifest with the provided IMG, not some default.  If it works without generation I totally agree it's better. If you can share your thoughts in form of branch/PR, would be great!

> 
> To solve the problem of polluting the repo with overwritten values I can think of following ways:
> 
> * create and share `.githooks` to prevent from accidentally committing wrong files. Such a hook (pre-commit?) can just reset the file to desired state
> * do the same as with the git-hook, but as GH Action
> 
> GH Action option does not require any contributor to set up git in a certain way. It will just work.
> 
> WDYT @ykaliuta @VaishnaviHire?

Well, it's a separate issue, I was more worried about my local repository state. Such a change easy to catch on review. It may make sense, but not at the file granularity, since commits to the file itself can be pretty legit.

PS: I'm so glad that finally it got attention. Sadly after it was committed.

**Comment by ykaliuta** [comment]
> > No, untracked files does not break git commit -a and is a least problem.
> 
> I stand corrected, though it makes a dirty state which is not ideal.
> 
> > If you can share your thoughts in form of branch/PR, would be great!
> 
> What I mean is as simple as following `kustomize.yaml`:
> 
> ```yaml
> apiVersion: kustomize.config.k8s.io/v1beta1
> kind: Kustomization
> 
> resources:
> - manager.yaml
> 
> generatorOptions:
>   disableNameSuffixHash: true
> 
> configMapGenerator:
> - files:
>   - controller_manager_config.yaml
>   name: manager-config
> 
> images:
> - name: controller
>   newName: quay.io/opendatahub.io/opendatahub-operator
>   newTag: latest
> ```
> 
> This will always work when using `kustomize` from CLI. It points to an existing image.
> 
> When you run `make deploy` it takes your `$(USER)` or any overwrite which is fine for dev purposes.
> 
> It brings back the problem you tried to solve in this PR,

Exactly

> but with the ideas from my original comment, we can prevent this from happening.

Prevent what? Pushing that change by accident? Yes. Polluting git commit -a? No.

What I'm trying to do is to avoid `git checkout config/manager/kustomization.yaml` before `git commit -a` when I do local development. Polishing the final pull request is a totally different issue.

> 
> > generated manifests should not be commited at all
> 
> That's entirely different conversation to have.

Yes, but related: we have autogenerated files (either it due to `kustomize edit` or `make manifests`) committed to the VCS which are changed without manual editing after clone/checkout and deploy.

> 
> > It may make sense, but not at the file granularity, since commits to the file itself can be pretty legit.
> 
> I would assume this file is stable enough to not really be worried about this, and even if, you can always think about some commit "directives" to make the change respected instead of being overwritten by the tool.
> 
> For example, a commit can have the following message: `chore(kustomize): updates manager settings #skip-kustomize-check`, and the tooling (disregard of what it is) will respect it.

Fine for me.

BTW, what the point of that chore/fix... in the commit _header_? It brings pretty much zero useful info but I'm sure I can miss some points.

> 
> With the `yaml.in` we are also losing a way to easily validate the manifests as this is not a standard kustomize structure.

Well, the yaml is generated with one make run.

I'm not fan of that solution either, just could not create anything better. And I saw in some other controllers that they use similar approach so decided that it's acceptable.

> 
> > PS: I'm so glad that finally it got attention. Sadly after it was committed.
> 
> It was annoying for me from day one, but wasn't that urgent to fix as I worked my way through it :)

**Comment by ykaliuta** [comment]
> Also... the file looks odd :D (not your fault, just sayin)
> 
> https://github.com/ykaliuta/opendatahub-operator/blob/53d81e4f966a93d6f04615d9baaba9784454f69c/config/manager/kustomization.yaml.in#L11-L12

Not my invention :) I copied the original file.

**Comment by bartoszmajsak** [comment]
> BTW, what the point of that chore/fix... in the commit header? It brings pretty much zero useful info but I'm sure I can miss some points.

https://www.conventionalcommits.org/en/v1.0.0/

**Comment by ykaliuta** [comment]
> > BTW, what the point of that chore/fix... in the commit header? It brings pretty much zero useful info but I'm sure I can miss some points.
> 
> https://www.conventionalcommits.org/en/v1.0.0/

Oh, so it's to increment semantic versions based on commit log. We are so far from it.

**Pull request merged**
