### PR TITLE
Add minKubeVersion to csv

### PR DESCRIPTION
**Pull request by VaishnaviHire**
This commit sets the `minKubeVersion` in csv to 1.18.0. This change prevents ODH operator from
being deployed on clusters with Kubernetes versions earlier than 1.18.0

Current supported versions of OpenShift: https://access.redhat.com/support/policy/updates/openshift#dates 

Issue: https://issues.redhat.com/browse/ODH-414

### CODE REVIEW

**Comment by LaVLaS** [comment]
We added `minKubeVersion` to all of the opendatahub-operators CSVs in the [community-operators](https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators/opendatahub-operator) repo. We need to sync those CSVs back to opendatahub-io because those CSVs also have the annotation `olm.properties: '[{"type": "olm.maxOpenShiftVersion", "value": "4.8"}]'`

From an offline discussion, the RH supported OCP is `kubernetes 1.18.0` but we should be setting this to `1.16.0` for OCP 4.3  (or 4.2 w/ 1.14.0) even though they are end of life

**Comment by VaishnaviHire** [comment]
> We added `minKubeVersion` to all of the opendatahub-operators CSVs in the [community-operators](https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators/opendatahub-operator) repo. We need to sync those CSVs back to opendatahub-io because those CSVs also have the annotation `olm.properties: '[{"type": "olm.maxOpenShiftVersion", "value": "4.8"}]'`
> 
> From an offline discussion, the RH supported OCP is `kubernetes 1.18.0` but we should be setting this to `1.16.0` for OCP 4.3 (or 4.2 w/ 1.14.0) even though they are end of life

Yes I will update the version to 1.14?

How do we sync the CSVs? Do I need to open a separate PR?

**Review by LaVLaS — APPROVED** [review]
/lgtm

**Comment by LaVLaS** [comment]
> How do we sync the CSVs? Do I need to open a separate PR?

Just to provide a public answer for anyone else, the [community-operators-prod](https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators/opendatahub-operator) repo is the source of truth for ODH operator in the OpenShift OperatorHub catalog.  That standard release process is update/add the CSV here and then duplicate the change to prod.  If any prod changes are made in that repo then we have to manually copy the entries back to this repo and commit the change

**Pull request merged**
