### PR TITLE
[sync]: change from incubation to rhoai + dummy change

### PR DESCRIPTION
**Pull request by zdtsw**
## Description

cherry-pick ODH change from incubation 
- https://github.com/opendatahub-io/opendatahub-operator/pull/1339
- https://github.com/opendatahub-io/opendatahub-operator/pull/1341
- dummy change to verify auto-sync is working 

https://issues.redhat.com/browse/RHOAIENG-15328

## Merge criteria

- [ ] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [ ] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [ ] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by ykaliuta** [comment]
Is "dummy change" required for the PR (Hint: `git commit --allow-empty`)

**Comment by zdtsw** [comment]
> Is "dummy change" required for the PR (Hint: `git commit --allow-empty`)

i am asked to explicitly do a change in that file as a dummy commit.

**Comment by ykaliuta** [comment]
> > Is "dummy change" required for the PR (Hint: `git commit --allow-empty`)
> 
> i am asked to explicitly do a change in that file as a dummy commit.

🙀 Ok

**Comment by zdtsw** [comment]
will need an approve to get this one out

**Review by lburgazzoli — APPROVED** [review]

**Pull request merged**
