### PR TITLE
Update: change apigroup for codeflare and dsp

### PR DESCRIPTION
**Pull request by zdtsw**
## Description

ref: #551 

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by zdtsw** [comment]
/hold
need confirm from https://github.com/opendatahub-io/data-science-pipelines-operator/blame/main/config/internal/apiserver/role_pipeline-runner.yaml.tmpl#L102 if still need `mcad` or dsp should clean it up too.

**Comment by zdtsw** [comment]
> /hold need confirm from https://github.com/opendatahub-io/data-science-pipelines-operator/blame/main/config/internal/apiserver/role_pipeline-runner.yaml.tmpl#L102 if still need `mcad` or dsp should clean it up too.

checked with DSP, https://redhat-internal.slack.com/archives/C05NXTEHLGY/p1695302105689869?thread_ts=1695224520.295299&cid=C05NXTEHLGY

**Review by VaishnaviHire — APPROVED** [review]
/lgtm

**Pull request merged**
