### PR TITLE
refactor(feature): decouples Feature from the client

### PR DESCRIPTION
**Pull request by bartoszmajsak**
## Description

Including the client in the function signature and decoupling it from `Feature` struct makes its usage explicit and more idiomatic. This approach clarifies that the client is intended for use within the function. 

It's a follow-up to PR [#1228](https://github.com/opendatahub-io/opendatahub-operator/pull/1228#issuecomment-2343046440).

## Merge criteria

- [x] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [x] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [x] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Needs #1235 to pass "unit tests" job

**Comment by lburgazzoli** [comment]
LGTM, defer to @zdtsw and @ykaliuta for final review

**Comment by zdtsw** [comment]
lgtm 

UsingClient() comes and goes :D

**Comment by zdtsw** [comment]
would be good to have this PR in ODH 2.18 since https://github.com/opendatahub-io/opendatahub-operator/pull/1228#issuecomment-2343046440 has been included. 
to have these 2 split into two releases is bit odd, but does no harm

**Review by ykaliuta — APPROVED** [review]

**Pull request merged**
