### PR TITLE
init: import code from rhods-operator 2.15 + new commits for 2.16 from incubation

### PR DESCRIPTION
**Pull request by zdtsw**
## Description

apart from listed jira,

- https://github.com/opendatahub-io/opendatahub-operator/pull/1310
- https://github.com/opendatahub-io/opendatahub-operator/pull/1311
- https://github.com/opendatahub-io/opendatahub-operator/pull/1322
- https://github.com/opendatahub-io/opendatahub-operator/pull/1327
- https://github.com/opendatahub-io/opendatahub-operator/pull/1254
- https://github.com/opendatahub-io/opendatahub-operator/pull/1336
- add support for 3 new annotation: cni csi cnf

Jira list
to fix: 
https://issues.redhat.com/browse/RHOAIENG-14768
https://issues.redhat.com/browse/RHOAIENG-14120
including:
+ https://issues.redhat.com/browse/RHOAIENG-15003
+ https://issues.redhat.com/browse/RHOAIENG-13411
+ https://issues.redhat.com/browse/RHOAIENG-13906
+ https://issues.redhat.com/browse/RHOAIENG-14189
+ https://issues.redhat.com/browse/RHOAIENG-9642

## How Has This Been Tested?

local build: quay.io/wenzhou/rhods-operator-catalog:v2.16.14768-2
install catalogsource
run e2e
```
go test ./tests/e2e/ -run ^TestOdhOperator -v --operator-namespace=redhat-ods-operator "--skip-deletion=true" -timeout 10m
=== RUN   TestOdhOperator
=== RUN   TestOdhOperator/validate_operator_pod_is_running
=== RUN   TestOdhOperator/validate_operator_pod_is_running/validate_RHOAI_Operator_pod
=== RUN   TestOdhOperator/validate_operator_pod_is_running/validate_CRDs_owned_by_the_operator
=== RUN   TestOdhOperator/validate_operator_pod_is_running/validate_CRDs_owned_by_the_operator/Validate_DSC_CRD
=== PAUSE TestOdhOperator/validate_operator_pod_is_running/validate_CRDs_owned_by_the_operator/Validate_DSC_CRD
=== RUN   TestOdhOperator/validate_operator_pod_is_running/validate_CRDs_owned_by_the_operator/Validate_DSCI_CRD
=== PAUSE TestOdhOperator/validate_operator_pod_is_running/validate_CRDs_owned_by_the_operator/Validate_DSCI_CRD
=== RUN   TestOdhOperator/validate_operator_pod_is_running/validate_CRDs_owned_by_the_operator/Validate_FeatureTracker_CRD
=== PAUSE TestOdhOperator/validate_operator_pod_is_running/validate_CRDs_owned_by_the_operator/Validate_FeatureTracker_CRD
=== CONT  TestOdhOperator/validate_operator_pod_is_running/validate_CRDs_owned_by_the_operator/Validate_DSC_CRD
=== CONT  TestOdhOperator/validate_operator_pod_is_running/validate_CRDs_owned_by_the_operator/Validate_FeatureTracker_CRD
=== CONT  TestOdhOperator/validate_operator_pod_is_running/validate_CRDs_owned_by_the_operator/Validate_DSCI_CRD
=== RUN   TestOdhOperator/create_Opendatahub_components
    helper_test.go:408: Ensuring serverless-operator is installed
    helper_test.go:408: Ensuring servicemeshoperator is installed
DEBUG WEN Subscription servicemeshoperator created
DEBUG WEN Subscription serverless-operator created
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test-dsc
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Creation_of_DSCI_CR
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Creation_of_more_than_one_of_DSCInitialization_instance
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_DSCInitialization_instance
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Check_owned_namespaces_exist
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Creation_of_DataScienceCluster_instance
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Creation_of_more_than_one_of_DataScienceCluster_instance
2024-11-02T17:50:52+01:00       INFO    KubeAPIWarningLogger    unknown field "spec.components.codeflare.component"
2024-11-02T17:50:52+01:00       INFO    KubeAPIWarningLogger    unknown field "spec.components.dashboard.component"
2024-11-02T17:50:52+01:00       INFO    KubeAPIWarningLogger    unknown field "spec.components.datasciencepipelines.component"
2024-11-02T17:50:52+01:00       INFO    KubeAPIWarningLogger    unknown field "spec.components.kserve.component"
2024-11-02T17:50:52+01:00       INFO    KubeAPIWarningLogger    unknown field "spec.components.kueue.component"
2024-11-02T17:50:52+01:00       INFO    KubeAPIWarningLogger    unknown field "spec.components.modelmeshserving.component"
2024-11-02T17:50:52+01:00       INFO    KubeAPIWarningLogger    unknown field "spec.components.modelregistry.component"
2024-11-02T17:50:52+01:00       INFO    KubeAPIWarningLogger    unknown field "spec.components.ray.component"
2024-11-02T17:50:52+01:00       INFO    KubeAPIWarningLogger    unknown field "spec.components.trainingoperator.component"
2024-11-02T17:50:52+01:00       INFO    KubeAPIWarningLogger    unknown field "spec.components.trustyai.component"
2024-11-02T17:50:52+01:00       INFO    KubeAPIWarningLogger    unknown field "spec.components.workbenches.component"
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_Ownerrefrences_exist
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_dashboard
=== PAUSE TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_dashboard
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_workbenches
=== PAUSE TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_workbenches
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_model-mesh
=== PAUSE TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_model-mesh
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_data-science-pipelines-operator
=== PAUSE TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_data-science-pipelines-operator
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_kserve
=== PAUSE TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_kserve
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_kueue
=== PAUSE TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_kueue
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_codeflare
=== PAUSE TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_codeflare
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_ray
=== PAUSE TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_ray
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_trustyai
=== PAUSE TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_trustyai
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_trainingoperator
=== PAUSE TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_trainingoperator
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_model-registry-operator
=== PAUSE TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_model-registry-operator
=== CONT  TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_dashboard
=== CONT  TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_codeflare
=== CONT  TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_data-science-pipelines-operator
=== CONT  TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_kueue
=== CONT  TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_model-mesh
=== CONT  TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_model-registry-operator
=== CONT  TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_kserve
=== CONT  TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_workbenches
=== CONT  TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_trustyai
=== CONT  TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_trainingoperator
=== CONT  TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_ray
2024/11/02 17:52:23 waiting for component deployments to be in Ready state: notebook-controller-deployment
2024/11/02 17:52:33 waiting for component deployments to be in Ready state: etcd
2024/11/02 17:52:43 waiting for component deployments to be in Ready state: etcd
2024/11/02 17:52:53 waiting for component deployments to be in Ready state: etcd
2024/11/02 17:53:13 waiting for component deployments to be in Ready state: data-science-pipelines-operator-controller-manager
2024/11/02 17:54:13 waiting for component deployments to be in Ready state: kserve-controller-manager
2024/11/02 17:54:23 waiting for component deployments to be in Ready state: kserve-controller-manager
2024/11/02 17:54:43 waiting for component deployments to be in Ready state: kueue-controller-manager
2024/11/02 17:55:03 waiting for component deployments to be in Ready state: codeflare-operator-manager
2024/11/02 17:55:23 waiting for component deployments to be in Ready state: trustyai-service-operator-controller-manager
2024/11/02 17:55:23 waiting for component deployments to be in Ready state: kuberay-operator
2024/11/02 17:55:33 waiting for component deployments to be in Ready state: trustyai-service-operator-controller-manager
2024/11/02 17:55:33 waiting for component deployments to be in Ready state: kuberay-operator
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_DSC_Ready
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_Knative_resoruce
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_default_certs_available
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_model_registry_cert_config
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_default_model_registry_cert_available
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_model_registry_servicemeshmember_available
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_Controller_reconcile
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_Component_Enabled_field
--- PASS: TestOdhOperator (497.23s)
    --- PASS: TestOdhOperator/validate_operator_pod_is_running (21.31s)
        --- PASS: TestOdhOperator/validate_operator_pod_is_running/validate_RHOAI_Operator_pod (10.73s)
        --- PASS: TestOdhOperator/validate_operator_pod_is_running/validate_CRDs_owned_by_the_operator (0.00s)
            --- PASS: TestOdhOperator/validate_operator_pod_is_running/validate_CRDs_owned_by_the_operator/Validate_FeatureTracker_CRD (10.48s)
            --- PASS: TestOdhOperator/validate_operator_pod_is_running/validate_CRDs_owned_by_the_operator/Validate_DSCI_CRD (10.48s)
            --- PASS: TestOdhOperator/validate_operator_pod_is_running/validate_CRDs_owned_by_the_operator/Validate_DSC_CRD (10.58s)
    --- PASS: TestOdhOperator/create_Opendatahub_components (475.91s)
        --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test-dsc (434.94s)
            --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Creation_of_DSCI_CR (10.60s)
            --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Creation_of_more_than_one_of_DSCInitialization_instance (0.30s)
            --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_DSCInitialization_instance (0.00s)
            --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Check_owned_namespaces_exist (0.20s)
            --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Creation_of_DataScienceCluster_instance (10.62s)
            --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Creation_of_more_than_one_of_DataScienceCluster_instance (0.27s)
            --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_Ownerrefrences_exist (0.17s)
            --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components (60.21s)
                --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_model-registry-operator (0.11s)
                --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_dashboard (0.11s)
                --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_trainingoperator (0.11s)
                --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_workbenches (40.23s)
                --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_model-mesh (70.23s)
                --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_data-science-pipelines-operator (90.12s)
                --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_kserve (160.12s)
                --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_kueue (180.12s)
                --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_codeflare (200.12s)
                --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_trustyai (230.12s)
                --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_all_deployed_components/Validate_ray (230.12s)
            --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_DSC_Ready (0.17s)
            --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_Knative_resoruce (0.00s)
            --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_default_certs_available (0.74s)
            --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_model_registry_cert_config (0.37s)
            --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_default_model_registry_cert_available (0.00s)
            --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_model_registry_servicemeshmember_available (0.00s)
            --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_Controller_reconcile (40.48s)
            --- PASS: TestOdhOperator/create_Opendatahub_components/e2e-test-dsc/Validate_Component_Enabled_field (80.47s)
PASS
ok      github.com/opendatahub-io/opendatahub-operator/v2/tests/e2e     497.242s
```

## Merge criteria

- [ ] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [ ] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [ ] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by VaishnaviHire** [comment]
@zdtsw I think we also need to add rhoai to openshift-ci config to run `rhoai` tests

**Comment by zdtsw** [comment]
finally! :joy:

**Comment by VaishnaviHire** [comment]
@zdtsw Update in deployment name to match with cpaas-midstream will be included in follow up PR?

**Comment by zdtsw** [comment]
> @zdtsw Update in deployment name to match with cpaas-midstream will be included in follow up PR?

updated in new commit, let e2e run and see how it goes

**Comment by VaishnaviHire** [comment]
Thanks for the changes! 

/lgtm

**Review by VaishnaviHire — APPROVED** [review]

**Pull request merged**
