### PR TITLE
Update TrustyAI Operator Variable

### PR DESCRIPTION
**Pull request by RobGeada**
Current variable does not match downstream image substitutions

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by zdtsw — APPROVED** [review]
/lgtm

**Review by VaishnaviHire — APPROVED** [review]
/lgtm

**Comment by zdtsw** [comment]
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/671

**Pull request merged**
