### PR TITLE
chore: cleanup remove kfdef during uninstallation

### PR DESCRIPTION
**Pull request by zdtsw**
- also clean kfdef reference

## Description

We have removed the cleanup during upgrade, not sure why this was left there during uninstallation.
The function is not necessary for any new releases.

## Merge criteria

- [ ] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [ ] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [ ] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by AjayJagan** [comment]
Great!! this will remove the dependency from v1 version and snyk will not complain :)

**Review by VaishnaviHire — APPROVED** [review]
/lgtm

**Pull request merged**
