### PR TITLE
WIP:  Add support for creating an ODH trusted CA Bundle during DSCInitialization reconciliation loop

### PR DESCRIPTION
**Pull request by LaVLaS**
## Description
Initial implementationfor creating an `odh-trusted-ca-bundle` ConfigMap in the DataScienceCluster namespace.  This will [inject](https://docs.openshift.com/container-platform/4.14/networking/configuring-a-custom-pki.html#certificate-injection-using-operators_configuring-a-custom-pki) the cluster-wide Trusted CA Bundle into the `.data["ca-bundle.crt"]` field of the ConfigMap via the Cluster Network Operator. 

Jira: [RHOAIENG-2465](https://issues.redhat.com/browse/RHOAIENG-2465)

Additionally, this adds a new `trustedCABundle` property in `DSCInitialization` for an admin to include a separate CA Certificate Bundle in the `.data["odh-ca-bundle.crt]` field of the `odh-trusted-ca-bundle` ConfigMap
This that can be used for centralizing the trusted CA Bundle for all ODH components to reference as part of the DSC deployment.

## How Has This Been Tested?
Local deployment in my development cluster 

Generated my own self signed certificate using `openssl` that is linked to other services that use TLS ([minio](https://min.io/docs/minio/linux/operations/network-encryption.html)

```
## Create a Self Signed Certificate using openssl
$ SELF_SIGNED_CERT_NAME=my-self-signed-cert
$ openssl req -newkey rsa:2048 -nodes -keyout ${SELF_SIGNED_CERT_NAME}.key -x509 -days 365 -out ${SELF_SIGNED_CERT_NAME}.crt
```

The CA bundle is a collection of encrypted certificates in text format.

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by zdtsw** [comment]
do we want to create this new CM, even dscInit.Spec.TrustedCABundle is "" ?

**Comment by VaishnaviHire** [comment]
Do we require end users to install the CNO operator , similar to what we do for servicemesh?

If yes, we would need to add a check to look for CNO subscription. (E.g https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/components/kserve/kserve.go#L213)

**Comment by LaVLaS** [comment]
> do we want to create this new CM, even dscInit.Spec.TrustedCABundle is "" ?

The ConfigMap contains two data files `ca-bundle.crt` and `odh-ca-bundle.crt` that would be potential VolumeMounts for pods in the ApplicationsNamespace.  

* `ca-bundle.crt` would be populated automatically by the Cluster Network Operator based on the `config.openshift.io/inject-trusted-cabundle` label. The file will always have this data field and it will automatically be updated based on the updates to the cluster trusted CA Bundle
* `odh-ca-bundle.crt` would be available for a volumeMount but I am hesitant to remove it on the chance that the field is updated to a null state while a pod has the configMap mounted to `odh-ca-bundle.crt`

**Comment by LaVLaS** [comment]
> Do we require end users to install the CNO operator , similar to what we do for servicemesh?
> 
> If yes, we would need to add a check to look for CNO subscription. (E.g https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/components/kserve/kserve.go#L213)

The CNO is installed by as a core dependency in OpenShift.  I am not aware of any scenario where is can be disabled in an OpenShift but definitely let me know if that is not the case

**Comment by LaVLaS** [comment]
Just an update: I am pausing this PR review while we discuss the design to create this `odh-trusted-ca-bundle` ConfigMap in ALL namespaces in preparation for the operator owning the management of ODH global artifacts in all namespaces

**Comment by VaishnaviHire** [comment]
Closing this since the changes are included in #848

**Pull request closed without merging**
