### PR TITLE
fix: dashboard image not get set in downstream due to devFlags config

### PR DESCRIPTION
**Pull request by zdtsw**
## Description

- if DSC CR has old format with empty devFlag:{}, it can cause downstream image not replace but run with quay.io one

https://issues.redhat.com/browse/RHOAIENG-12300

## How Has This Been Tested?

local build and test: 'quay.io/wenzhou/opendatahub-operator:2.12300.1'

steps:
create DSC CR with 
```
dashboard:
      devFlags: {}
      managementState: Managed
```
and
```
dashboard:
      managementState: Managed
```
does not trigger debug into `OverrideManifests`
use
```
dashboard:
      managementState: Managed
     devFlags:
         manifests: [
              uri: "https://wen.zhou.com"
          ]
         }
```
into error, expected,` "https://wen.zhou.com\": dial tcp: lookup wen.zhou.com on 172.30.0.10:53: no such host",`

## Merge criteria

- [ ] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [ ] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [ ] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by lburgazzoli — APPROVED** [review]

**Review by andrewballantyne — APPROVED** [review]
LGTM based on your comment on the ticket. Great tracing down this legacy issue

**Comment by ykaliuta** [comment]
Honestly, I'm confused. if d.DevFlags != nil it should call d.OverrideManifests where it checks  len(d.DevFlags.Manifests) != 0

**Comment by zdtsw** [comment]
> Honestly, I'm confused. if d.DevFlags != nil it should call d.OverrideManifests where it checks len(d.DevFlags.Manifests) != 0

yep yep, the tricky part is, it does as you said, but then it  skipped:
```
} else { // Update image parameters if devFlags is not provided
			imageParamMap["odh-dashboard-image"] = "RELATED_IMAGE_ODH_DASHBOARD_IMAGE"
}
```

**Comment by ykaliuta** [comment]
ah, ok, thanks!

**Pull request merged**
