### PR TITLE
Splitting distributed workflows component into codeflare and ray. Fixes #369

### LINKED ISSUE #369: Update distributed workloads to sub components
Add `codeflare` and `kuberay` as separate components instead of one component of `distributedworkloads

### PR DESCRIPTION
**Pull request by etirelli**
This PR includes the following:

* changes the API removing distributedworkloads property and adding codeflare and ray
* supports codeflare installation
* does NOT install ray, although it does add ray in the CR spec
* updates the templates and docs
* Fixes #369

This PR has been manually tested in the cluster and does NOT loop on reconciliation.

## Merge criteria:
- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by zdtsw** [comment]
@etirelli I think you need to run "`make generate`" in order to get Ray populate into `deepcopy` and `config/crd/bases` etc

the current changes does not expose Ray as component to user

**Comment by etirelli** [comment]
@zdtsw Thank you, I will take a look because I did run make generate and compiled and I am currently testing the PR. However there is more to do (I need to create an additional configuration for instaScale) so please do not merge this.
I had labeled this PR as work-in-progress, but the openshift-ci removed my label... :/

**Review by VaishnaviHire — APPROVED** [review]
/lgtm

**Comment by zdtsw** [comment]
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/384

**Pull request merged**
