### PR TITLE
manager: adjust cpu request to 100m and memory to 512Mi

### PR DESCRIPTION
**Pull request by ykaliuta**
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/578

## Description

Existing limits garantee the operator to run but are too agressive

So, decrease memory limit to the reasonable 2Gi and CPU request to 100m

## How Has This Been Tested?

Run make e2e-test

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by VaishnaviHire** [comment]
Hi @ykaliuta , changes look good. However we need to test this by setting all components to `managementState:Managed`

You can build a custom bundle to do so - https://github.com/opendatahub-io/opendatahub-operator#deployment

**Comment by zdtsw** [comment]
lets wait for QE to get some baseline from nightly first and see how much we are using for now.

**Comment by kpouget** [comment]
Hello, I had a look at the PR, I see that it updates the `requests`  of the operator Pod (more memory, less CPU)
I confirm that performance wise, this PR is fine. Under any normal circumstances, the hardware `requests` does not have any impact on the performance, only the `limits` which isn't touched here.

**Comment by zdtsw** [comment]
i tested on the current "incubation" branch with all Components set to Managed (GA + TA)
you can see the peak in both mem and cpu (i would assume, this could be the case when a new operator just installed into cluster) 
Screenshot from 2023-12-13 12-47-40
654Mi / 0.209m

**Comment by ykaliuta** [comment]
> i tested on the current "incubation" branch with all Components set to Managed (GA + TA) you can see the peak in both mem and cpu (i would assume, this could be the case when a new operator just installed into cluster)
So, should I drop the PR?

**Pull request closed without merging**
