### PR TITLE
chore(mesh): Use third party service account tokens

### PR DESCRIPTION
**Pull request by israel-hdez**
## Description
This should allow Service Mesh to run on any OpenShift flavor.

Fixes opendatahub-io/kserve#138

## How Has This Been Tested?
Manually, depoying Service Mesh with the operator.

## Merge criteria:
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by zdtsw** [comment]
has this been verified on real Managed cluster?

**Review by spolti — APPROVED** [review]

**Comment by israel-hdez** [comment]
> has this been verified on real Managed cluster?

Nope. I don't know how to do that.

**Comment by israel-hdez** [comment]
> is this intended for 2.5 downstream release? or just good to have in ODH for incubation?

Good to have for incubation.

**Review by zdtsw — APPROVED** [review]
/lgtm

we can get this into ODH incubatin first and see if we can test in different cluster type as it is not urgent to have in 2.5/2.6

**Comment by bartoszmajsak** [comment]
>  ## How Has This Been Tested?
> Manually, depoying Service Mesh with the operator

@israel-hdez what cluster have you used for that?

**Comment by israel-hdez** [comment]
> > Manually, depoying Service Mesh with the operator
> 
> @israel-hdez what cluster have you used for that?

PSI :-)

**Comment by israel-hdez** [comment]
@VaishnaviHire would you give your final approval here?

**Comment by zdtsw** [comment]
what i am thinking is, if it is too difficult to get dev test covering on all clusters, we can merge this in and run odh nightly on PSI, Managed and hybrid to get a quick verification.

**Comment by israel-hdez** [comment]
> what i am thinking is, if it is too difficult to get dev test covering on all clusters, we can merge this in and run odh nightly on PSI, Managed and hybrid to get a quick verification.

I'm good with this approach...

**Comment by zdtsw** [comment]
@VaishnaviHire how you feel about this PR?

**Comment by israel-hdez** [comment]
@zdtsw @VaishnaviHire A reminder to, please, follow-up

**Comment by zdtsw** [comment]
take the liberty since  @VaishnaviHire is on vacation,  i will get this merged and  lets see if any issue afterwards

**Pull request merged**
