### PR TITLE
fix: reworks reconcilation resource check

### PR DESCRIPTION
**Pull request by bartoszmajsak**
This change removes `.Get` call in favor of a single `.List` operation to check for resource existence. In addition, the check for deletion timestamp has been fixed, as previously it was performed on the newly instantiated object instead of it being first synced with cluster, where this field is set.

### CODE REVIEW

**Review by zdtsw — APPROVED** [review]
/lgtm

**Comment by bartoszmajsak** [comment]
@zdtsw I think it requires yet another `/lgtm` :)

**Review by zdtsw — APPROVED** [review]
/lgtm

**Review by etirelli — APPROVED** [review]
lgtm

**Pull request merged**
