### PR TITLE
Fix imagestream watch

### PR DESCRIPTION
**Pull request by anishasthana**
Signed-off-by: Anish Asthana <anishasthana1@gmail.com>

### CODE REVIEW

**Review by crobby — APPROVED** [review]
I have tested this...it works.

**Comment by anishasthana** [comment]
The test failure seemed "correct". I'll get the reconciliation change in via a separate PR.

**Review by LaVLaS — APPROVED** [review]

**Comment by crobby** [comment]
Oh man, now we get burned by....
```
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 88
Current browser version is 90.0.4430.72 with binary path /usr/bin/google-chrome
```

**Comment by crobby** [comment]
Once the odh-manifests test pass again, it will promote the fixed test image and then a retest here should work.

**Pull request merged**
