### PR TITLE
feat: add post-check on the params.env file for workbench images

### PR DESCRIPTION
**Pull request by zdtsw**
## Description

it is not clear in some cases, nbc image did not get properly swapped. and this is causing, nbc pod keeping trying to pull image which does not exist, e.g in disconnected env a quay.io image wont/shouldnt be there for use
often this is fixed by restart nbc deployment. 
root cause still unclear for now.

this PR is only to add a post check and if it does not work then reconcile again.
- to prevent failure when components accidentally pull down wrong image
- check is on certain keywords, e.g new image pullspec but can be extend to any string

https://issues.redhat.com/browse/RHOAIENG-11368

## Merge criteria

- [ ] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [ ] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [ ] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by ykaliuta** [comment]
Do you mean, that params.env does not get updated by ApplyParams() call?

Is it correct Jira?

**Comment by zdtsw** [comment]
> Do you mean, that params.env does not get updated by ApplyParams() call?
> 
> Is it correct Jira?

i got the wrong number from the reporter and pasted the wrong one, corrected now

**Comment by ykaliuta** [comment]
> 
> i got the wrong number from the reporter and pasted the wrong one, corrected now

Ok, read the problem. So, is it ApplyParams call does not change params.env (what the PR addresses IIUC) or it's not called at all? There are no comments in the Jira

**Comment by zdtsw** [comment]
> Do you mean, that params.env does not get updated by ApplyParams() call?
> 
> Is it correct Jira?

it is hard to know what exactly happened at that point of time.
either the params.env did not get updated? or it gets updated but kustomize did not use it? 
it is a very rare case, and it can be "auto fix" because component gets reconciled.
but if reconcile did not get triggered, then workbench (so far several cases only reported on workbench) pod is trying to pull image set as the default value in params.env

**Pull request closed without merging**
