### PR TITLE
Use OLM dependency for Prometheus installation

### PR DESCRIPTION
**Pull request by VannTen**
## Description

This uses the dependency mechanism of the Operator Lifecycle Manager to express that ODH needs to use the prometheus-operator CR. Docs : https://olm.operatorframework.io/docs/concepts/olm-architecture/dependency-resolution/

@anishasthana Is it what you were mentionning ?
@LaVLaS

### CODE REVIEW

**Comment by VannTen** [comment]
Note that it might be relevant to put those deps directly in each odh which will directly use them (model-mesh or dashboard for example)

**Comment by VannTen** [comment]
Another point:
- ServiceMonitor Rules, etc, shoud live in the same repo than the metrics they target, IMO (=> metrics produced from odh-model-controller -> ServiceMonitor in odh-model-controller + Rule -> production, collection and aggregation of the metrics is defined in the same place)

**Comment by VannTen** [comment]
@cfchase Might want to look as well.

**Comment by shalberd** [comment]
Hmm, why not enable monitoring for user-defined projects? Available both in OKD and OCP. https://docs.okd.io/4.10/monitoring/enabling-monitoring-for-user-defined-projects.html The prometheus monitoring stack on Openshift already has a monitoring stack for central cluster projects (kube*, openshift*) and, when Monitoring for User Defined Projects is enabled, for all other projects / namespaces. Would be an easy way to enable monitoring in all namespaces where KfDefs are defined. In the sense of not reinventing the wheel.

**Comment by shalberd** [comment]
> * ServiceMonitor Rules, etc, shoud live in the same repo than the metrics they target, IMO (=> metrics produced from odh-model-controller -> ServiceMonitor in odh-model-controller + Rule -> production, collection and aggregation of the metrics is defined in the same place)

Yes, that is true even with Monitoring for User Defined Projects. ServiceMonitor, PodMonitor, PrometheusRule CRs. 

With Clusterrole monitoring-edit assigned via a namespace-specific rolebinding, for example, users can create and delete those CRs in a namespace. To see the Observe Web GUI, they also need to have at least the Clusterrole view assigned via a namespace-specific rolebinding.

**Comment by VannTen** [comment]
Multiples reasons:
1. We don't control the enablement of user-workloads monitoring.
2. Isolation of the metrics stack. Other metrics source can make Prometheus unstable, if some kind of cardinality explosion happens.
3. This avoids depending on Openshift. I'm not sure how much odh is tied to Openshift currently but not adding additional dependencies on it is nice.

Ideally, the Prometheus CR should be optional, so the choice is left to users (and to downstream) to use it or not ; I need to check how that's done with the operator-sdk format.

**Comment by VaishnaviHire** [comment]
Closing this since it is out of date

**Pull request closed without merging**
