### PR TITLE
fix: only replace/set default model reg namespace by webhook if comnent is enabled

### PR DESCRIPTION
**Pull request by zdtsw**
## Description

these two cases should not block operation, for backwards compataible
- when modelreg is not set in DSC
- when modelreg is set to be Removed 

https://issues.redhat.com/browse/RHOAIENG-13052

## How Has This Been Tested?

local build: quay.io/wenzhou/opendatahub-operator-catalog:v2.18.13052

## Merge criteria

- [ ] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [ ] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [ ] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by CFSNM — APPROVED** [review]

**Comment by ykaliuta** [comment]
So back to my question do we really need that webhook when there is default value? Is it against explicit "" value?

**Comment by zdtsw** [comment]
> So back to my question do we really need that webhook when there is default value? Is it against explicit "" value?

better to have an example for this question.
e.g modelreg has a default namespace set but to value "" ? and it is in Managed?

**Comment by ykaliuta** [comment]
> > So back to my question do we really need that webhook when there is default value? Is it against explicit "" value?
> 
> better to have an example for this question. e.g modelreg has a default namespace set but to value "" ? and it is in Managed?

modelregistry has // +kubebuilder:default="odh-model-registries". So, if I put no RegistriesNamespace in the DSC, I see odh-model-registries there. The only case when len can be 0, IIUC, is setting it explicitly to "".

**Comment by zdtsw** [comment]
> > > So back to my question do we really need that webhook when there is default value? Is it against explicit "" value?
> > 
> > 
> > better to have an example for this question. e.g modelreg has a default namespace set but to value "" ? and it is in Managed?
> 
> modelregistry has // +kubebuilder:default="odh-model-registries". So, if I put no RegistriesNamespace in the DSC, I see odh-model-registries there. The only case when len can be 0, IIUC, is setting it explicitly to "".

yep, see 
https://github.com/opendatahub-io/opendatahub-operator/pull/1221#discussion_r1752265224
https://github.com/opendatahub-io/opendatahub-operator/pull/1221#discussion_r1755640985

**Review by ykaliuta — APPROVED** [review]

**Comment by zdtsw** [comment]
> > > > > So back to my question do we really need that webhook when there is default value? Is it against explicit "" value?
> > > > 
> > > > 
> > > > better to have an example for this question. e.g modelreg has a default namespace set but to value "" ? and it is in Managed?
> > > 
> > > 
> > > modelregistry has // +kubebuilder:default="odh-model-registries". So, if I put no RegistriesNamespace in the DSC, I see odh-model-registries there. The only case when len can be 0, IIUC, is setting it explicitly to "".
> > 
> > 
> > yep, see [#1221 (comment)](https://github.com/opendatahub-io/opendatahub-operator/pull/1221#discussion_r1752265224) [#1221 (comment)](https://github.com/opendatahub-io/opendatahub-operator/pull/1221#discussion_r1755640985)
> 
> It sounds as a pretty weird case. I can understand that user can forget to set some value. But why user should explicitly set it to a wrong value? Is it the only value like that (that user can break the system)? What about applicationNamespace in DSCI?

in theory, if explictily set "" for applicationnamespace in DSCI
say, in a clean installed cluster,  no "opendatahu" namesapce exist,
it will be a problem for component:  applicationamespace has a default value "opendatahub" but the namespace is not crated by createOdhNamespace due to "" string.
thats why in the downstream, we are creating DSCI on the fly for user upon installation. 
but yes, this is a tricky question

**Pull request merged**
