### PR TITLE
(chore): Comment the 'push version tag to quay.io' step in gh action

### PR DESCRIPTION
**Pull request by AjayJagan**
Commenting the 'push version tag to quay.io' step in gh action because this will need verification from DevOps if we have enough rights to push to quay-odh repo.

## Description
Commenting the 'push version tag to quay.io' step in gh action because this will need verification from DevOps if we have enough rights to push to quay-odh repo.

## Merge criteria

- [ ] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [ ] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [ ] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by VaishnaviHire — APPROVED** [review]
/lgtm

**Comment by ykaliuta** [comment]
Why not to just remove it? You have version control, it will not be lost.

**Comment by AjayJagan** [comment]
> Why not to just remove it? You have version control, it will not be lost.

So it is like a temporary commenting of the code, to check the automation for the current release. Once I have discussed it with devops, I will uncomment it back

**Comment by ykaliuta** [comment]
> > Why not to just remove it? You have version control, it will not be lost.
> 
> So it is like a temporary commenting of the code, to check the automation for the current release. Once I have discussed it with devops, I will uncomment it back

So why not to just remove it? You have version control, it will not be lost. You can always revert the patch.

**Pull request merged**
