### PR TITLE
Add Opendatahub-operator pod selector label

### PR DESCRIPTION
**Pull request by vaibhavjainwiz**
Add Opendatahub-operator pod selector label. Same is used in ODS_CI test suits to validate operator pod is running.
https://github.com/vaibhavjainwiz/ods-ci/blob/support_odh/ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot#L77

Similliar label is already a part of rhods-operator.

I am doing this change as an effort to enable ODS_CI testsuit for ODH testing as well.

## Description

https://issues.redhat.com/browse/RHOAIENG-5321

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by AjayJagan — APPROVED** [review]
/lgtm

**Comment by zdtsw** [comment]
i would prefer to only use cpaas PR1913  which address the internal build system for ODH-nightly.

**Comment by zdtsw** [comment]
wanna hear how @VaishnaviHire feel about this PR
my concern is for the upgrade case in ODH release.

**Comment by vaibhavjainwiz** [comment]
till now ODS_CI test are compatible to work with `odh-nightlies` and `rhods-operator` only. 
for `rhods-operator` label with name `name=rhods-operator` is already passed as a pod selector label.(https://redhat-internal.slack.com/archives/D05FX3MHX46/p1712831085045729)
For odh-nightlies , we have conditional check in ODS_CI to skip the verification of pod running status.
https://github.com/red-hat-data-services/ods-ci/blob/master/ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot#L73.

Now I am working on a task to enable ODS_CI test for ODH codebase as general use case.
I had left with 2 option in my case :
- Either add more conditional check in ODS_CI to skip the verification of pod running status.
- Or Add the missing label in codebase
I am following the second approach and adding the missing label

**Review by VaishnaviHire — APPROVED** [review]
/lgtm

**Comment by VaishnaviHire** [comment]
This change looks good to me, should not break upgrade

**Pull request merged**
