### PR TITLE
Update ODH operator to reconcile updated objects

### PR DESCRIPTION
**Pull request by anishasthana**
Signed-off-by: Anish Asthana <anishasthana1@gmail.com>

### CODE REVIEW

**Comment by anishasthana** [comment]
@LaVLaS CI is passing now if you can take a look. :-)

**Review by crobby — COMMENTED** [review]
This looks reasonable.  I'll try and test drive this later on.

**Review by crobby — APPROVED** [review]
Nice, simple change.  I've seen it work. Works great.

**Comment by accorvin** [comment]
I am working on testing this change.

**Pull request merged**
