### PR TITLE
Rename variables rhods to rhoai

### PR DESCRIPTION
**Pull request by ajaypratap003**
## Description

Rename variables RHODS to RHOAI

https://issues.redhat.com/browse/RHOAIENG-9642

## Merge criteria

- [ ] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [ ] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [ ] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by zdtsw** [comment]
i am fine with this change, but need rebase @ajaypratap003

**Comment by VaishnaviHire** [comment]
/lgtm

@ajaypratap003 PR needs a rebase

**Comment by zdtsw** [comment]
rebase in https://github.com/opendatahub-io/opendatahub-operator/pull/1313

**Comment by ykaliuta** [comment]
> rebase in #1313

why not here?

**Pull request closed without merging**
