### PR TITLE
fix: to make the unset env variable in CSV work with fallback

### PR DESCRIPTION
**Pull request by zdtsw**
## Description

- previous code, will run into "opendathaub" case if env is not set
- change make in both "not set" and "set to empty string" fall back to old logic with auto detection

related to change from  https://github.com/opendatahub-io/opendatahub-operator/pull/1252

## Merge criteria

- [ ] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [ ] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [ ] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by ykaliuta** [comment]
Will it be ok if "" just removed from the first case? So, if environment variable matches, it switches to the that, if it is not set or does not match -- fallback to detection.

**Comment by zdtsw** [comment]
> Will it be ok if "" just removed from the first case? So, if environment variable matches, it switches to the that, if it is not set or does not match -- fallback to detection.

the main difference will be: if set to "" should be treated as Unknow or OpenDataHub.
but i dont have stronge opinion on this, if we do not need it to be OpenDataHub, it can be much simple -- taking away the if {} in default-case

**Comment by ykaliuta** [comment]
> > Will it be ok if "" just removed from the first case? So, if environment variable matches, it switches to the that, if it is not set or does not match -- fallback to detection.
> 
> the main difference will be: if set to "" should be treated as Unknow or OpenDataHub. but i dont have stronge opinion on this, if we do not need it to be OpenDataHub, it can be much simple -- taking away the if {} in default-case

I vote for the simple case :) Until there are reasons not to do it

**Comment by zdtsw** [comment]
> > > Will it be ok if "" just removed from the first case? So, if environment variable matches, it switches to the that, if it is not set or does not match -- fallback to detection.
> > 
> > 
> > the main difference will be: if set to "" should be treated as Unknow or OpenDataHub. but i dont have stronge opinion on this, if we do not need it to be OpenDataHub, it can be much simple -- taking away the if {} in default-case
> 
> I vote for the simple case :) Until there are reasons not to do it

updated

**Review by VaishnaviHire — APPROVED** [review]

**Pull request merged**
