### PR TITLE
Update TrustyAI operator version to 1.11.0

### PR DESCRIPTION
**Pull request by ruivieira**
## Description

Update TrustyAI operator to latest upstream release [v1.11.0](https://github.com/trustyai-explainability/trustyai-service-operator/releases/tag/v1.11.0).

## How Has This Been Tested?

Locally with DSC and `trustyai` component.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by zdtsw — APPROVED** [review]
/lgtm

**Comment by zdtsw** [comment]
@ruivieira can you rebase this first?

**Comment by zdtsw** [comment]
normally, component team choose to use "main"/"master" branch, so we do not need to update this file all the time on incubation branch.
only when we do odh release, we use "release" tag (or branch)

in workbenches case, since they do not use main/master, thats why you see it is a release branch.
i am not sure if you should use  release branch in your case? or this change is for odh 1.11 only

**Comment by ruivieira** [comment]
> normally, component team choose to use "main"/"master" branch, so we do not need to update this file all the time on incubation branch. only when we do odh release, we use "release" tag (or branch)
> 
> in workbenches case, since they do not use main/master, thats why you see it is a release branch. i am not sure if you should use release branch in your case? or this change is for odh 1.11 only

@zdtsw good point. For TrustyAI, we use `main` for development and do release branches.
In `main` we use the image pair `trustyai-service-operator:latest`/`trustyai-service:latest` and in the release branches we fix the tags (e.g. in this case `trustyai-service-operator:1.11.0`/`trustyai-service:0.6.0`.

We can discuss what strategy fits better with ODH operator offline if that's ok. I'll close this PR anyway, just because we'll have a fix release with important updates.

**Pull request closed without merging**
