### PR TITLE
feat: add managed model registry prometheus config handling logic, fixes RHOAIENG-4273

### PR DESCRIPTION
**Pull request by dhirajsb**
## Description

Adds managed model registry prometheus config handling logic
Fixes RHOAIENG-4273

https://issues.redhat.com/browse/RHOAIENG-4273

## How Has This Been Tested?

Tested that the code changes do not affect ODH unit tests. 
Further testing of the actual prometheus config will continue for other PR https://github.com/red-hat-data-services/rhods-operator/pull/318
But no component code changes will be needed for any changes in the prometheus config. 

## Merge criteria

- [X] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [X] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [X] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by dhirajsb** [comment]
WIP, working on changes to model registry operator metrics service configuration. I need to locally test model registry to verify whether extra manifests are neeeded in `prometheus/metrics/apps manifests`.

**Comment by dhirajsb** [comment]
@ykaliuta is there an easy way to combine the config logic from this PR and prometheus config in the PR https://github.com/red-hat-data-services/rhods-operator/pull/318 to test them together? 
Or, should I manually setup the prometheus config in a local cluster to verify?

**Comment by ykaliuta** [comment]
> @ykaliuta is there an easy way to combine the config logic from this PR and prometheus config in the PR [red-hat-data-services#318](https://github.com/red-hat-data-services/rhods-operator/pull/318) to test them together? Or, should I manually setup the prometheus config in a local cluster to verify?

Do you mean to have a branch with all the changes? Rebase 1150 on top of 318, it depends of it. Basically, they should come as one patchset in one PR if we did not have that squashing policy. But even squashing them in one patch does not look a problem for me in this case.

Or I'm missing something?

**Comment by zdtsw** [comment]
/LGTM

I am fine with this change. @dhirajsb 
I said in the offline chat.  as long as the logic wont break ODH build,and regression, it can get into the code base.

But you two have started discussion of how it should be tested^ so I leave it to you to finalize that before the final call.

In general, I would say, this is a tricky topic: as we have not decided how should this specific monitoring be handled in ODH. Plus, it gets a bit challenge to fully test it by Devel.  One thing can be done as @ykaliuta mentioned, cherry-pick this change onto downstream's PR and make build from there to test. or vice versa.

**Comment by ykaliuta** [comment]
> 
> Or I'm missing something?

Yes, different branches :) But anyway, as @zdtsw said.

**Comment by dhirajsb** [comment]
@zdtsw let's merge this boilerplate code for odh 2.16 since it's exactly the same as all other rhoai components. 

I'll continue working on testing the actual prometheus yaml config on the other RHDS PR https://github.com/red-hat-data-services/rhods-operator/pull/318

**Review by zdtsw — APPROVED** [review]

**Comment by zdtsw** [comment]
@VaishnaviHire + @dhirajsb FYI, i wont sync this PR into downstream 2.12 for now. 
we can let it be in ODH 2.16 first and get the downstream config changes later in nightly along with this PR.

**Pull request merged**
