### PR TITLE
Specify full x.y.z version of Go in go.mod

### PR DESCRIPTION
**Pull request by grdryn**
-------

JIRA: https://issues.redhat.com/browse/RHOAIENG-16819

## Description

It seems like on some platforms, when the local installation
installation of Go decides that it needs to download a different
toolchain, that it may fail unless we either specify a full x.y.z
version in the `go` directive, or explicitly specify the `toolchain`
directive.

I believe for our uses, using a fully specified x.y.z `go` directive
value is preferable, to prevent any issues with explicitly defining a
toolchain where we might have a newer version in a container image
build that has a default of `GOTOOLCHAIN='local'` (I'm not 100% sure
if that would cause any issues, but I'm 100% sure that the way
proposed in this commit shouldn't).

## How Has This Been Tested?

- builds fine
- runs fine

## Merge criteria

- [x] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [x] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [x] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by grdryn** [comment]
/cc @VaishnaviHire 

This is a follow up to #1439 after feedback in https://github.com/opendatahub-io/opendatahub-operator/pull/1440#issuecomment-2535902872

**Comment by VaishnaviHire** [comment]
/lgtm

needs rebase ;(

**Comment by ykaliuta** [comment]
> 
> needs rebase ;(
does it?

**Comment by grdryn** [comment]
> needs rebase ;(

I wonder if that was a GH blip, or a change with how it works? :thinking: I also saw that message that it was out of date with the base branch, but now it says the following for me, which seems to indicate that it'll get auto-merged fine once it gets the approved label:

image

**Comment by ykaliuta** [comment]
> > needs rebase ;(
> 
> I wonder if that was a GH blip, or a change with how it works? 🤔

No idea, I checked the merge itself :)

**Review by VaishnaviHire — APPROVED** [review]
/lgtm

**Pull request merged**
