### PR TITLE
Rebase to kfctl master

### PR DESCRIPTION
**Pull request by vpavlin**
Rebase to commit [1dceb1497c444a015bf947299ef8e9f6c86af75b](https://github.com/kubeflow/kfctl/commit/1dceb1497c444a015bf947299ef8e9f6c86af75b)

### CODE REVIEW

**Comment by vpavlin** [comment]
@crobby @nakfour @LaVLaS Can you take a look again - I pushed a set of commits matching opendatahub-operator/master and Github closed the PR as merged..so I had to create a new one.

**Comment by vpavlin** [comment]
NOTE: Do not forget to merge as "Rebase and merge" to make sure we do not polute master with merge commits

**Comment by crobby** [comment]
For me, github seems hung on "checking for ability to merge automatically"...anyone else seeing this?  @vpavlin @LaVLaS @nakfour

**Comment by crobby** [comment]
> For me, github seems hung on "checking for ability to merge automatically"...anyone else seeing this? @vpavlin @LaVLaS @nakfour

Nevermind...after I commented, it "unfroze"

**Pull request closed without merging**
