### PR TITLE
upgrade(go): use 1.20

### PR DESCRIPTION
**Pull request by zdtsw**
upgrade to use registry.access.redhat.com/ubi8/go-toolset:1.20 as base image

## Description

ref: https://issues.redhat.com/browse/RHOAIENG-2045

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by ajaypratap003 — COMMENTED** [review]
LGTM

**Comment by VaishnaviHire** [comment]
Do we need to update operator-sdk as well that maps to go 1.20?

**Comment by zdtsw** [comment]
> Do we need to update operator-sdk as well that maps to go 1.20?

Good idea!

the latest sdk version 1.33 is on go 1.21
i upgraded ours to 1.31 which is the latest one built upon go 1.19

we can try with 1.33+ once we upgrade our go to 1.21 in half year.

**Comment by bartoszmajsak** [comment]
@zdtsw any reason why we can't bump to 1.21 yet?

**Comment by zdtsw** [comment]
> @zdtsw any reason why we can't bump to 1.21 yet?

for some reason that we dont have 1.21 go-tools image ready for downstream yet....

**Comment by zdtsw** [comment]
for internal build to work , we need PR 1850 in as well.

**Comment by ykaliuta** [comment]
Do you need formal ACK for the PR?

In general I would like to discuss would it be possible to have the version in one place instead of 4. One of the possibility in my mind:
- have the version in go.mod. It's needed for go infrastructure to work properly anyway.
- get the version in the Makefile (a-la ```GO_VERSION=$(shell sed -n '/^go/s/go \(.*\)/\1/p' < go.mod)``` )
- remove default value for go version from the dockerfiles
- pass the version to image builder as the mandatory argument

**Comment by VaishnaviHire** [comment]
> Do you need formal ACK for the PR?
> 
> In general I would like to discuss would it be possible to have the version in one place instead of 4. One of the possibility in my mind:
> 
> * have the version in go.mod. It's needed for go infrastructure to work properly anyway.
> * get the version in the Makefile (a-la `GO_VERSION=$(shell sed -n '/^go/s/go \(.*\)/\1/p' < go.mod)` )
> * remove default value for go version from the dockerfiles
> * pass the version to image builder as the mandatory argument

I think the only thing we need to confirm here if we can pass these arguments during CPaaS build

**Comment by ykaliuta** [comment]
> > I think the only thing we need to confirm here if we can pass these arguments during CPaaS build

Good point, but don't they use own midstream Dockerfile.in instead of ODH repo's ones?

**Comment by zdtsw** [comment]
> > > I think the only thing we need to confirm here if we can pass these arguments during CPaaS build
> 
> Good point, but don't they use own midstream Dockerfile.in instead of ODH repo's ones?

- tools image not sure if this is in any use.
- the real operator image can get Go version passed from makefile (similar to what is being done in the tools image)
but i think the reason why we set the version in Dockerfile is to decouple "make" and "build image": otherwise, without makefile , cannot build image or have to pass env for "build" command.
- i think this ^ is the same reason for "get Go version from go.mod and set it in makefile"

we will still need to update midstream with proper base image for different  Go version.
so the manually work will be needed than "sync" work from odh to downstream

**Review by ykaliuta — APPROVED** [review]

**Pull request merged**
