### PR TITLE
Merge feature-operator-refactor branch

### PR DESCRIPTION
**Pull request by VaishnaviHire**
## Merge criteria

- [ ] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [ ] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [ ] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by ykaliuta** [comment]
Since the feature branch was very work in progress, it does not make sense to keep all the patches (actually, patch names only) in the final merge. It just pollutes the log without carrying any useful information. Especially taking into account that it will be squashed in one patch.

On the other hand since the branch was not rebased  on top on the incubation, it makes following the changes on the branch a bit more difficult.

I see at least two options:
1) keep it in review as is but put on hold and make final squashing manually with a clear commit message.
2) make the rebase on the feature branch itself (and do PR from a separate branch anyway with a clear commit message :). It will allow to compare the branches with just `git diff`

**Comment by VaishnaviHire** [comment]
> I see at least two options:
> 
> 1. keep it in review as is but put on hold and make final squashing manually with a clear commit message.
> 2. make the rebase on the feature branch itself (and do PR from a separate branch anyway with a clear commit message :). It will allow to compare the branches with just `git diff`

I like the idea of having it first merged to feature branch. I updated the base for this PR. (cc: @lburgazzoli @zdtsw )

**Comment by zdtsw** [comment]
> > I see at least two options:
> > 
> > 1. keep it in review as is but put on hold and make final squashing manually with a clear commit message.
> > 2. make the rebase on the feature branch itself (and do PR from a separate branch anyway with a clear commit message :). It will allow to compare the branches with just `git diff`
> 
> I like the idea of having it first merged to feature branch. I updated the base for this PR. (cc: @lburgazzoli @zdtsw )

so the final goal is to get all new "refactor" changes into incubation branch.
and this is the one to prepare for the feature-operator-refactor to get the "newer" commits from incubation since it was branched out ?

but isnt it easier, 
- wait till all "refactor parts" are done on feature-operator-refactor branch (which is modelmesh + api uplift + monitorservice + nim) 
- cherry-pick a handful newer  commits (date back from 2nd Oct)  from incubation:  makefile change + github action + init startup (needed? or just skip ) + logging part ( needed? or just skip) + pre-check for servicemesh + some small fixes
- test everything on feature-operator-refactor
- final force merge from feature-operator-refactor to incubation as a PR
- done

**Comment by VaishnaviHire** [comment]
Closing this one. As discussed offline, next steps - 

1. Maintain `main` branch with all changes
     a. We will create `main` off of feature branch
     b. Do a merge from `incubation`

**Pull request closed without merging**
