### PR TITLE
Remove old component interface

### PR DESCRIPTION
**Pull request by lburgazzoli**
- old and unused Component interface removed
- UpdatePrometheusConfig function moved to pkg/services/monitoring

## Merge criteria

- [x] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [x] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [x] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [ ] ~~Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).~~
- [ ] ~~The developer has manually tested the changes and verified that the changes work~~

### CODE REVIEW

**Review by zdtsw — APPROVED** [review]

**Comment by zdtsw** [comment]
need update dockerfile.

**Comment by lburgazzoli** [comment]
> need update dockerfile. https://github.com/lburgazzoli/opendatahub-operator/blob/cleanup-old-components/Dockerfiles/Dockerfile#L31

done

**Review by zdtsw — APPROVED** [review]

**Review by VaishnaviHire — COMMENTED** [review]
/lgtm

**Pull request merged**
