### PR TITLE
Changed variable name for cfo operator image

### PR DESCRIPTION
**Pull request by Bobbins228**
## Description

Changed the variable name `odh-codeflare-operator-controller-image` to `codeflare-operator-controller-image`
Relates to: [PCF CFO #398](https://github.com/project-codeflare/codeflare-operator/pull/398)
## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by Bobbins228** [comment]
@zdtsw Do you mind taking a look at this whenever you get a chance?

**Comment by zdtsw** [comment]
which this change you will need to update odh-codeflare-operator-controller-image in a bunch of places to make it work https://github.com/opendatahub-io/codeflare-operator/blob/8c83032e747cbaa6f281bebe359351cd22f3a221/config/manifests/bases/params.env#L2
is this the plan? 
if so, good to have your changes in upstream (codeflare project) done first and have a draft in opendatahub-io codeflare operator

**Comment by Bobbins228** [comment]
> with this change you will need to update odh-codeflare-operator-controller-image in a bunch of places to make it work https://github.com/opendatahub-io/codeflare-operator/blob/8c83032e747cbaa6f281bebe359351cd22f3a221/config/manifests/bases/params.env#L2 is this the plan? if so, good to have your changes in upstream (codeflare project) done first and have a draft in opendatahub-io codeflare operator

Hi Wen, 
That is the plan so we should have this change merged in PCF/CFO first, sync it to the ODH/CFO then merge this PR?

**Comment by zdtsw** [comment]
> > with this change you will need to update odh-codeflare-operator-controller-image in a bunch of places to make it work https://github.com/opendatahub-io/codeflare-operator/blob/8c83032e747cbaa6f281bebe359351cd22f3a221/config/manifests/bases/params.env#L2 is this the plan? if so, good to have your changes in upstream (codeflare project) done first and have a draft in opendatahub-io codeflare operator
> 
> Hi Wen, That is the plan so we should have this [change](https://github.com/project-codeflare/codeflare-operator/pull/398) merged in PCF/CFO first, sync it to the ODH/CFO then merge this PR?

if this change gets merged in ODH operator ahead of CFO in ODH, it probably wont do any harm, since the logic is only for the RHOAI, but if ODH operator sync to RHOAI and the  CFO in RHOAI not get updated then it will break RHOAI.
since it is not anything consumed by any other party except RHOAI operator, i think it is safe to get it done from CFO side first.

**Review by astefanutti — COMMENTED** [review]
project-codeflare/codeflare-operator#398 also changes the path from which the ODH operator should source the CodeFlare operator manifests.

My understanding is that this path should be updated somewhere?

**Comment by astefanutti** [comment]
@zdtsw The PR on CodeFlare operator side has been merged project-codeflare/codeflare-operator#398. Can this one be merged as well. Thanks!

**Review by astefanutti — APPROVED** [review]

**Comment by astefanutti** [comment]
> * should we wait for the sync done in https://github.com/opendatahub-io/codeflare-operator?

Right, we should wait for the sync to be done.

> * i thought the PR is only to change variable name but seems it also changed the path of where manifests are located?
>   hard for me to see this change of "removing bases and use manager than manifests" reflects to what is in [Added Workflow job to update CFO image project-codeflare/codeflare-operator#398](https://github.com/project-codeflare/codeflare-operator/pull/398), could you confirm this is indeed required?

Right, it's not obvious. I confirm project-codeflare/codeflare-operator#398 changes the location of the manifests has changed from `/config/manifests/bases` to `/config/manager`.

**Comment by zdtsw** [comment]
> > * should we wait for the sync done in [opendatahub-io/codeflare-operator](https://github.com/opendatahub-io/codeflare-operator)?
> 
> Right, we should wait for the sync to be done.
> 
> > * i thought the PR is only to change variable name but seems it also changed the path of where manifests are located?
> >   hard for me to see this change of "removing bases and use manager than manifests" reflects to what is in [Added Workflow job to update CFO image project-codeflare/codeflare-operator#398](https://github.com/project-codeflare/codeflare-operator/pull/398), could you confirm this is indeed required?
> 
> Right, it's not obvious. I confirm [project-codeflare/codeflare-operator#398](https://github.com/project-codeflare/codeflare-operator/pull/398) changes the location of the manifests has changed from `/config/manifests/bases` to `/config/manager`.


sure, but then you probably would need to update https://github.com/Bobbins228/opendatahub-operator/blob/rename-cfo-variable/components/codeflare/codeflare.go#L23 as well @Bobbins228

**Review by zdtsw — APPROVED** [review]

**Comment by zdtsw** [comment]
btw, we will also need to sync this change for RHOAI.
if you plan to get it from ODH to RHOAI in next release 2.7, both changes should land at the same time.

**Comment by astefanutti** [comment]
> btw, we will also need to sync this change for RHOAI. if you plan to get it from ODH to RHOAI in next release 2.7, both changes should land at the same time.

Right. The plan is to get it into RHOAI 2.7. @Bobbins228 @VanillaSpoon Could you please sync with @zdtsw once the CF/CFO change is synced in ODH, thanks!

**Comment by zdtsw** [comment]
/ohhold

if the final plan is to use "default" than "manager" waiting for new commits to arrive

**Review by VaishnaviHire — APPROVED** [review]
/lgtm

**Comment by Bobbins228** [comment]
@zdtsw @astefanutti 
ODH/CFO has the changes [synced](https://github.com/opendatahub-io/codeflare-operator/commit/233de7ea5f895ef5be319386f437f46d3bdde048) are we clear to merge?

**Comment by zdtsw** [comment]
> @zdtsw @astefanutti ODH/CFO has the changes [synced](https://github.com/opendatahub-io/codeflare-operator/commit/233de7ea5f895ef5be319386f437f46d3bdde048) are we clear to merge?

i am fine with this PR, as long as you've update CFO to use default

**Comment by astefanutti** [comment]
> > @zdtsw @astefanutti ODH/CFO has the changes [synced](https://github.com/opendatahub-io/codeflare-operator/commit/233de7ea5f895ef5be319386f437f46d3bdde048) are we clear to merge?
> 
> i am fine with this PR, as long as you've update CFO to use default

@zdtsw @Bobbins228 This looks good to me. @Bobbins228 can you double check and confirm everything is in place?

**Comment by Bobbins228** [comment]
@astefanutti It looks good to me also image is updated in the manager folder and kustomize path is set to default,
> i am fine with this PR, as long as you've update CFO to use default
@zdtsw bit confused on the wording here

**Comment by zdtsw** [comment]
> @astefanutti It looks good to me also image is updated in the manager folder and kustomize path is set to default,
> 
> > i am fine with this PR, as long as you've update CFO to use default
> 
> @zdtsw bit confused on the wording here

@Bobbins228 , what i meant is as long as in the odh codeflare operator the manifests have been moved into "default" folder, then i am good with the change in this PR.

**Review by zdtsw — APPROVED** [review]

**Pull request merged**
