### PR TITLE
Add examples annotation, add spec and status descriptors

### PR DESCRIPTION
**Pull request by maroroman**
Resolves: #189

## Description
The scorecard tests were tested and do work as-is on the current bundle. However, there was one error:

            --------------------------------------------------------------------------------
            Image:      quay.io/operator-framework/scorecard-test:v1.23.0
            Entrypoint: [scorecard-test olm-crds-have-resources]
            Labels:
                    "suite":"olm"
                    "test":"olm-crds-have-resources-test"
            Results:
                    Name: olm-crds-have-resources
                    State: fail
            
                    Errors:
                            Owned CRDs do not have resources specified
                    Log:
                            Loaded ClusterServiceVersion: opendatahub-operator.v0.0.1

And 5 annotation warnings:

            Warning: Value dashboard.opendatahub.io/v1, Kind=OdhApplication: provided API should have an example annotation
            Warning: Value opendatahub.io/v1alpha, Kind=OdhDashboardConfig: provided API should have an example annotation
            Warning: Value dashboard.opendatahub.io/v1, Kind=OdhDocument: provided API should have an example annotation
            Warning: Value console.openshift.io/v1, Kind=OdhQuickStart: provided API should have an example annotation
            Warning: Value kfdef.apps.kubeflow.org/v1, Kind=KfDef: provided API should have an example annotation

Therefore this PR, on top of testing the scorecard tests, also attempts to resolve these warnings and error.

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by maroroman** [comment]
The alm-examples are just some copied manifests, I am not sure if we intend to make some kind of sample manifests for this instead.

 I also did not go too deep when it comes to the CRD properties, mostly only those that show up in the samples.

**Comment by VaishnaviHire** [comment]
@maroroman Following up from our conversation regarding removing the CRD spec validation test. Is this ready to merge?

**Comment by maroroman** [comment]
If we want to keep the descriptors and examples as they are, the PR should be ready for merging now

**Review by VaishnaviHire — APPROVED** [review]
/lgtm

**Pull request merged**
