### PR TITLE
feat: uses reflect to reconcile defined components

### PR DESCRIPTION
**Pull request by bartoszmajsak**
## Description

In this PR, I would like to propose a streamlined approach to component reconciliation by leveraging Go's `reflect` package. This eliminates the necessity for manual reconciliation whenever a new component is introduced. As a result, we achieve consistent handling regardless of the number of components.

## How Has This Been Tested?

- smoke tested using [dashboard+workbenches DSC](https://gist.github.com/bartoszmajsak/89d71235e64c0c78bb65685ba95ae572). Custom controller image: `quay.io/maistra-dev/opendatahub-operator:dev-reflect`

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by zdtsw — APPROVED** [review]
/lgtm

**Comment by zdtsw** [comment]
as offline discussed, for any component requires special handling in the future, we can add logic handling in "component"

**Comment by bartoszmajsak** [comment]
@VaishnaviHire @zdtsw would be great if we could make it merged. I tested this on service-mesh branch extensively and it works fine.

**Comment by bartoszmajsak** [comment]
Closing in favor of rebased version #593

**Pull request closed without merging**
